### ISSUE TITLE
Insecure old MuPDF is used by default

### ISSUE THREAD

**Issue by linsui** [foobnix/LibreraReader#1030]
There are many known security issues in the old MuPDF lib (see https://divestos.org/misc/appsec.txt) so it's marks with KnownVule in F-Droid (https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11496).

It was removed but then added back. Currently it's the default render so that it's also used on newer Android versions. I'd like to set the new MuPDF as the default render for F-Droid with a simple patch. And it may be better to set the default value based on the Android version. Will that cause any problem?

**Comment by chemicalcain** [comment]
Foobnix has limited ability to work on the app right now due to the Russian invasion of Ukraine, but it looks like pull requests get handled pretty quickly. @linsui do you think you could patch out old MuPDF and create a pull request? Foobnix would still be able to look over the patch before merging into the master branch.

**Comment by linsui** [comment]
I'll change the default setting. I thought it's not difficult to patch out the old MuPDF lib but it's added back for compatibility so I'd rather keep it. Maybe it's enough to patch https://github.com/foobnix/LibreraReader/blob/9b9c166913cc73a5ff669e695a67c8109bd23995/app/src/main/java/com/foobnix/pdf/info/AppsConfig.java#L30 to `MuPDF_1.11(Vulnerable!)`.

**Comment by chemicalcain** [comment]
Compatibility is definitely important. Can MuPDF 1.11 be isolated so it is only accessed on Android versions not compatible with the newer MuPDF?

**Comment by linsui** [comment]
It's poosible but I thought we need to wait the dev for such a change.

**Comment by pickinanameainteasy** [comment]
While we wait for an update, I assume just changing the engine to MuPDF_1.20.4 will keep us safe?

**Comment by linsui** [comment]
Yes.

**Comment by sandoxy** [comment]
Is it not save to use this APP? What kind of risk would it be?

**Comment by linsui** [comment]
If you open a malicious pdf with the old engine you are in risk.

**Comment by sandoxy** [comment]
Thank you for the answer. Will be there an update soon, so I could use this APP savely again?

**Comment by pickinanameainteasy** [comment]
Click the hamburger menu in the top left hand corner, scroll down to engine and select MuPDF_1.20.4.

MuPDF_1.11 is the vulnerable version.

**Comment by sandoxy** [comment]
> Click the hamburger menu in the top left hand corner, scroll down to engine and select MuPDF_1.20.4.
> 
> MuPDF_1.11 is the vulnerable version.

Wow, great, now I can reinstall the APP on my phone!

**Comment by foobnix** [comment]
fixed in 8.8.15

**Comment by soshial** [comment]
The latest version of Librera now weighs 35 MiB instead of 66 MiB, that's amazing! Thanks, @foobnix

**Comment by pickinanameainteasy** [comment]
Thanks! Stay safe.
