### ISSUE TITLE
[Issue] [Beta] [MuPDF 1.21.1] EPUB footnote linking doesn't work correctly

### ISSUE THREAD

**Issue by Teashrock** [foobnix/LibreraReader#1046]
**The bug**:
I was compiling a epub-book in Sigil for myself, but have encountered a problem soon: in-text footnote links redirect totally not to what is intended.

**Example**:
Chapter 1, link number 1 should lead to footnote "c1s1", but instead, it leads to footnote "c7s1". The same time, Chapter 7, link number 1 leads to "c7s1" as it should.

**Expected behaviour**:
1. Open Chapter 1.
2. Click link number 1.
3. Be redirected to "c1s1".

**What happens instead**:
1. Open Chapter 1.
2. Click link number 1.
3. Be redirected to "c7s1".

**The files in question**:

chapter1.xhtml:
```XHTML
«Ну, ты родился
на Канарских островах, да и если бы я назвала тебя George, мы бы
не могли звать тебя Джоджо, ведь так?»<a id="anc1" href="footnotes.xhtml#c1s1"><sup>[1]</sup></a> Моего отца, погибшего в кораблекрушении, звали Джонатан Джостар, и всю его жизнь люди
звали его Джоджо;
```

chapter7.xhtml:
```XHTML
Если бы не англичане,
возвращение Канарских островов к испанцам произошло бы куда легче<sup><a id="c7s1" href="footnotes.xhtml#c5s1">[1]</a></sup>.
```

footnotes.xhtml:
```XHTML
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Сноски</title>
</head>

<body>
  <p>1.1 <a id="c1s1" href="chapter1.xhtml#anc1>Jorge/George — для русского языка обе эти надписи звучат "Джордж", и потому разница в написании значения не имеет. Однако, для английского языка традиционно это имя пишется "George". Jorge — испанская версия этого имени, читающаяся как Хорхе, из-за чего местные и называют так главного героя.</a></p><br/>
  ...
  <p>7.1 <a id="c7s1" href="chapter7.xhtml#c7a1">Британский флот за свою историю несколько раз совершал попытки захвата у испанцев Канарских островов. Первое нападение произошло в 1595 году, в 1657 году Британия разгромила испанские войска, а в 1797 году попытка захвата повторилась. Официально Канары стали провинцией Испании лишь в 1821 году.</a></p><br/>
</body>
</html>
```

**Comment by foobnix** [comment]
please attach or send a book by email librera.reader@gmail.com

**Comment by foobnix** [comment]
The problem in Librera is with footer note numbers in the page text.
Librera not support  the same [1] number in many chapters, the number should be unique 1,2 ... 100, ++ etc
for example, problem will be here
chapter 1, note [1]
chapter 2, note [1] //1 is duplicated

Correct should be 
chapter 1, note [1]
chapter 2, note [2]
or
chapter 1, note [1.1] 
chapter 2, note [2.1]

Ivan

**Comment by Teashrock** [comment]
@foobnix 
And is there really no way to fix it?

**Comment by Teashrock** [comment]
The question is that a sufficient amount of sites with books and fanfics make EPUB books in this very format. And almost every other book reader supports it. It's a pity that I have to use proprietary premium-limited ReadEra in favor of open-source and free Librera just because specifically the latter doesn't support this mechanism.

Besides, as I understand, you're Ukrainian like me, so an open-source free reader from a Ukrainian developer is something I'd want to use. This behavior is the only con.

**Comment by foobnix** [comment]
Added in beta.librera.mobi :)
Please test as many books as possible, something might be broken

**Comment by Teashrock** [comment]
@foobnix 
I'll check, thank you very much! Downloaded the beta version, it now works as intended! But I won't close the issue yet, because I'll need to check other books.

Offtopic question to avoid creating a separate issue: what is the exact difference between Librera, Librera F-Droid, and Librera Pro? What are the pros and cons of each version? Thank you in advance.

**Comment by Teashrock** [comment]
Switched on to MuPDF 1.21.1, then opened the first chapter in two-page mode. But the footnote shows nothing! If I switch back to one-page mode, everything works as intended.

Two-page mode:
![Screenshot_20230123_095625](https://user-images.githubusercontent.com/12483854/214071489-9ca715e6-12f1-45ff-838e-034d3be9d444.jpg)

One-page mode:
![Screenshot_20230123_095745](https://user-images.githubusercontent.com/12483854/214071288-230258b0-c15d-4693-92c8-9855d8ff2a55.jpg)

**Comment by foobnix** [comment]
fixed in beta
