### ISSUE TITLE
Cannot apply custom font.

### ISSUE THREAD

**Issue by ThomasLeigh** [foobnix/LibreraReader#1047]
After upgrading to ver. 8.8.15-fdroid (1211-fdroid) my custom font does not appear within books I read. I tried to set this font once again - to no avail. The font file is still present where it has been before. 

Before the upgrade the font worked only with MuPDF 1.11 - switching to the ver. 1.21.1 resulted in the font not working. In the newest Librera I cannot switch to the older MuPDF.

Could the ability to apply custom fonts from .ttf files placed within Librera/fonts folder be restored?

**Comment by CR0CKER** [comment]
Confirming this issue. Same on two different devices (phone and eBook reader).

**Comment by wsldankers** [comment]
In my case I can't even select the pre-included fonts, like DejaVu. Only some of the available fonts (like Helvetica, Times New Roman) can be selected, the others result in a fallback to some serif font.

**Comment by Korb** [comment]
I confirm, version 8.8.15-fdroid on Vivo T1 (V2153, 4G) does not allow changing the font to arbitrary without error messages. In most cases, some default serif font is used.

```
Версия ОС: Funtouch OS 13 Global
Версия аппаратного обеспечения: МР_0.1
Номер сборки: PD2201OF_EX_A_13.1.13.1.W20.V000L1
Прошивка модуля связи: MPSS.HA.1.1 .С2-00012-KD_ALL_PACK-1.6347.66
Версия ядра: 4.19.157-perf+ #1 Thu Dec 1 12:15:36 CST 2022
Время компиляции: 1 дек. 2022 г. 07:03:09
Обновление системы через Google Play: 1 ноября 2022 г.
```

**Comment by jumper047** [comment]
I can confirm too, just rolled back to 8.8.5-fdroid.4855 and font selection works again

**Comment by foobnix** [comment]
please check beta.librera.mobi version, and if not works, please send a book sample

**Comment by CR0CKER** [comment]
Seems to work with the beta version! Tested on two devices and noticed no issues. Thanks for the fix!
