### ISSUE TITLE
[Issue] [Beta] [MuPDF 1.11] Different cover image rendering

### ISSUE THREAD

**Issue by Teashrock** [foobnix/LibreraReader#1048]
**The bug**:
Cover image in the same file renders differently on Librera F-Droid stable and Librera Beta. The latter adds two empty pages around the image, while the former doesn't.

Stable version:
![Screenshot_20230120_024523](https://user-images.githubusercontent.com/12483854/213594078-d9b41ce7-08fd-4dfd-96ca-7cac853fdbbe.jpg)

Beta version:
![Screenshot_20230120_024714](https://user-images.githubusercontent.com/12483854/213594176-b2fbd1e6-7df4-41e0-99ae-31c5b8206d28.jpg)
![Screenshot_20230120_024720](https://user-images.githubusercontent.com/12483854/213594195-cf6be417-6d0f-432e-abba-bdef65a49f35.jpg)

**Expected behaviour**:
Beta version should behave like the stable version.

**Attached file**:
The same I sent to you in #1046.

**Comment by Teashrock** [comment]
This bug has disappeared on the latest beta, so closing this for now.

**Comment by Teashrock** [comment]
Reopening again. The bug is absent on MuPDF 1.21.1, but is present on MuPDF 1.11.

**Comment by foobnix** [comment]
Can't reproduce in the final beta version

**Comment by foobnix** [comment]
fixed in beta
