### ISSUE TITLE
Play Store review prompt appears in F-Droid version

### ISSUE THREAD

**Issue by Scrounger2082** [foobnix/LibreraReader#1058]
I would assume many or most people using F-Droid do not use the Google Play Store or use an alternative like the Aurora Store. Also this may be considered an F-Droid antifeature but I'm not sure.

![Screenshot_20230206-105136_Librera FD_1](https://user-images.githubusercontent.com/121117961/216953260-cc29b125-b940-4041-ab5d-36394d3af4ca.png)

**Comment by foobnix** [comment]
fixed in new beta
