### ISSUE TITLE
Feature request: library shortcut in bottom toolbar when reading

### ISSUE THREAD

**Issue by chemicalcain** [foobnix/LibreraReader#1059]
Current behavior: In order to go to the library page from inside a book, I must press the system Back button and choose "Open Library." Since I prefer Librera in fullscreen mode, this is three actions: swipe to show system navbar (or exit fullscreen), press Back, and press Open Library. 

I would prefer if there was a shortcut to go to the Library in one click next to the Recent Books button. It would be much faster.

**Comment by foobnix** [comment]
Excellent idea! Added in the [beta.librara.mobi](https://www.dropbox.com/home/FREE_PDF_APK/testing)
