### ISSUE TITLE
no CBR 

### ISSUE THREAD

**Issue by metbic** [foobnix/LibreraReader#1060]
Viewing CBR files does not work. I'm not 100% sure if it's supposed to work.
Tested machines (Librera 8.8.15-fdroid installed): Google Pixel w/ Android 13; CBR file doesn't open. Sony Xz1c w/ Android 9; Librera crashes but reopens immediately, CBR file doesn't open.
Sorry if this is an redundant or duplicate issue.
Best of luck and godspeed.

**Comment by foobnix** [comment]
fdroid not support cbr due to licence, please use librera PRO with cbr support
