### ISSUE TITLE
Feature request: more natural TTS voices through VALL-E-like models

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [foobnix/LibreraReader#1062]
Would it be possible to use a state of the art generative model to produce speech with the proper intonation and pauses, for use in the TTS Reader Android app?

**Comment by foobnix** [comment]
it's not depend on my app, just choose TTS engine you like

**Comment by wassname** [comment]
I'm using SoTA voice in Librera through [kaldi next gen](https://github.com/k2-fsa/sherpa-ncnn)
