### ISSUE TITLE
Add reactions and a comment group to the app's telegram channel

### ISSUE THREAD

**Issue by Korb** [foobnix/LibreraReader#1066]
(https://t.me/LibreraReader)

Reactions will give you a rough idea of the relative value of the changes introduced to the application. The group will help users of the application to help each other in non-obvious things when using the added functions, in solving problems without opening tickets on github and contacting the developer personally.

**Comment by foobnix** [comment]
https://t.me/librera_reader_chat

**Comment by Korb** [comment]
Did you decide not to allow reactions in the channel?

![2023-02-24_13-08-54](https://user-images.githubusercontent.com/3509797/221151839-6457cb61-836f-4bbc-b9c9-554a198c6f9a.png)

**Comment by foobnix** [comment]
Reactions should be enabled

**Comment by Korb** [comment]
They are enabled in the group but not in the channel. The channel properties should look like this:

![2023-02-24_13-57-22](https://user-images.githubusercontent.com/3509797/221162546-4582b89f-fdaa-45a6-b668-4d2f60bf5dec.png)

**Comment by foobnix** [comment]
done
