### ISSUE TITLE
Librera 8.8.15 MuPDF to 1.21.1 error

### ISSUE THREAD

**Issue by Dog404** [foobnix/LibreraReader#1068]
MuPDF to 1.21.1 error，[Librera 8.8.15]
![20230224125950](https://user-images.githubusercontent.com/85744951/221095985-2eb8bdd5-97e4-4d20-96e9-f37170162dfc.png)
Switch to MuPDF_1.11 for normal display
![20230224130227](https://user-images.githubusercontent.com/85744951/221096312-62266aff-7897-432b-9fa0-ff64a76b102a.png)

**Comment by foobnix** [comment]
Please attend or send book/page sample by email

**Comment by Dog404** [comment]
发件人: Ivan Ivanenko ***@***.***>
发送时间: 2023年2月24日 14:22
收件人: foobnix/LibreraReader ***@***.***>
抄送: Dog404 ***@***.***>; Author ***@***.***>
主题: Re: [foobnix/LibreraReader] Librera 8.8.15 MuPDF to 1.21.1 error (Issue #1068)


Please attend or send book/page sample by email

**Comment by foobnix** [comment]
Please send a book sample to librera.reader@gmail.com

**Comment by Dog404** [comment]
The problem has been located, CSS stylesheet has errors
