### ISSUE TITLE
App crashed after browsing last JPEG in a CBZ file.

### ISSUE THREAD

**Issue by YorkJong** [foobnix/LibreraReader#1070]
And I cannot reset the progress for a CBZ.
After that, it crashes every time when I open the CBZ.

Android 9

**Comment by foobnix** [comment]
Please send file sample by email I cant reproduce librera.reader@gmail.com

**Comment by YorkJong** [comment]
I found the cause while making the minima test CBZ file.
I compressed those CBZ on my MacBook.
And they contain a _MACOSX system folder in the compressed ZIP files.
Remove the _MACOSX folder on my Android can avoid the problem.

**Comment by foobnix** [comment]
In any case, you can send me the sample file; maybe I can ignore this folder

**Comment by YorkJong** [comment]
The attachment is the sample file.
I compressed the zip file on macOS.

Thank you.

**Comment by foobnix** [comment]
fixed cover for cbz in new beta
