### ISSUE TITLE
LibreraReader not showing 「」

### ISSUE THREAD

**Issue by Theakkk** [foobnix/LibreraReader#1073]
Hey, the reader is not showing 「」in an epub, which is used to show a person talking in a novel and I encounter this same problem in other novels also. But the epub shows 「」when I open it on PC. This problem made it pretty much impossible to read novels because all the conversations are enclosed in 「」. Can you please suggest a fix for it?

**Comment by Theakkk** [comment]
I'm using the latest version btw.

**Comment by foobnix** [comment]
Please check the final beta.librera.mobi
Could you please send a book sample if the chars are not showing?
