### ISSUE TITLE
Can`t create profile directory with "/"

### ISSUE THREAD

**Issue by MerQGh** [foobnix/LibreraReader#1075]
I have a device with name "Sharp Aquos S2 4/64". When Librera started, it try to create dir with same name. But two separate dirs created: "device.Sharp_Aquos_S2_4" and "64". Next time Librera can't find profile dir and can't store last book, progress, etc. Can you add "/" in replace list, such as " "?
Librera FD 8.8.40-fdroid

**Comment by foobnix** [comment]
fixed in new beta
