### ISSUE TITLE
How to delete a tag?

### ISSUE THREAD

**Issue by N3tFX** [foobnix/LibreraReader#1079]
How can I delete a tag from Librera? In the FAVORITES tab there are tags that I don't use any more and I can't find a way to completely remove them from the app.

**Comment by foobnix** [comment]
You can remove tags here 
![Screenshot-2023-03-22-12-21-59](https://user-images.githubusercontent.com/432440/226874217-ff70188c-72d2-44a0-af2f-c03b6d7f83f2.png)

**Comment by N3tFX** [comment]
I did that, but the tags are still shown in the list below with a zero in parentheses **(0)**. Could the problem be that I deleted the documents outside librera (with a file manager)?
