### ISSUE TITLE
[8.8.76] Chapter headers are not rendering in night mode

### ISSUE THREAD

**Issue by Teashrock** [foobnix/LibreraReader#1081]
When I switch to night mode reading, headers in the start of each chapter are not rendering. In day reading mode everything is normal.

**Version**: 8.8.78 (111-pro)

**EPUB file**:
https://dropmefiles.com.ua/ua/2zW5PR8

**System**:
Android 13

**Device**:
Samsung Galaxy Tab S6 Lite

**Note**:
The issue persists with both MuPDF 1.11 and 1.21.1.

**Screenshots**:

Day mode:
![Screenshot_20230324_011558](https://user-images.githubusercontent.com/12483854/227387216-72fd756f-868f-4c2d-8207-5b67dc6fc655.jpg)

Night mode:
![Screenshot_20230324_011614](https://user-images.githubusercontent.com/12483854/227387223-b4ba177b-6968-4167-b307-387964dd7938.jpg)

**Comment by foobnix** [comment]
thanks, fixed in beta.librera.mobi

**Comment by Teashrock** [comment]
@foobnix 
Excuse me, but I can't find the beta version. There is only 8.8.76 in beta.librera.mobi.

**Comment by Teashrock** [comment]
Oops, forget it. My bad.
