### ISSUE TITLE
Rename the file for export backups

### ISSUE THREAD

**Issue by MrComexs** [foobnix/LibreraReader#1083]
I do backups every once and a while. When I export my backup its named
` YYYY-MM_DD-HH-mm-export-backup.zip`
How do you feel about adding Librera to the file's name. Here is some examples
`librera-YYYY-MM_DD-HH-mm-export-backup.zip`
`YYYY-MM_DD-HH-mm-librera-export-backup.zip`
`YYYY-MM_DD-HH-mm-export-backup.librera.zip`
`YYYY-MM_DD-HH-mm-export-backup.librera`

Reason for why I think why this should be a feature is because a lot of other apps do have very similar back file names so it gets confusing. If I were to choice I would like any of them but not the 2 second one but still better then nothing.

Thank you for time.

**Comment by foobnix** [comment]
fixed in beta
