### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [foobnix/LibreraReader#1091]
Please support the Android 13 "Themed App Icons" feature.

![Screenshot_2023-04-08-02-17-16-859_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/230689778-e820fe00-8800-4992-a9da-1f2c64cff93a.jpg)

**Comment by foobnix** [comment]
Please check in beta
![Screenshot-2023-04-10-11-22-54](https://user-images.githubusercontent.com/432440/230861931-05759595-a1bb-45f1-b7ba-deb9b7679f9d.png)

**Comment by xmha97** [comment]
Thanks 🙏
