### ISSUE TITLE
Bionic Reading mode

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [foobnix/LibreraReader#1095]
This is a new way to read faster (making first few characters of a word bold)
https://www.google.com/url?sa=i&url=https%3A%2F%2Fbionic-reading.com%2F&psig=AOvVaw1unojsvnqf2nwOeiowuWrQ&ust=1681373206729000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCPi6wbfxo_4CFQAAAAAdAAAAABAG

Would be nice to have a setting which transforms the text in this way.

**Comment by foobnix** [comment]
will be in beta today
![Screenshot-2023-04-12-12-16-48](https://user-images.githubusercontent.com/432440/231412755-742f0cd1-73d4-4436-89e1-fec798b686a3.png)
![Screenshot-2023-04-12-12-16-29](https://user-images.githubusercontent.com/432440/231412765-2eae89fe-d8cd-40ec-8ece-b04b4e414ebd.png)

**Comment by dhruv-anand-aintech** [comment]
Wonderful. Thank you!

**Comment by foobnix** [comment]
done, please check in beta.librera.mobi
