### ISSUE TITLE
A possible solution for CBR

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [foobnix/LibreraReader#1097]
By integrating this library it’s possible to decode CBR format.
https://github.com/zeniko/unarr

**Comment by foobnix** [comment]
CBR is supported in Librera PRO but not in F-Droid version

**Comment by KrasnayaPloshchad** [comment]
But with this library it’s possible to make F-Droid version get support as well.

**Comment by foobnix** [comment]
Unarr has licence that not compatible with fdroid rules

**Comment by KrasnayaPloshchad** [comment]
Yeah, I’m sorry to see, but I’ve see another library to support this format, and it’s a open-source library:
https://github.com/libarchive/libarchive
[https://opengraph.githubassets.com/7ac74fce03e1e41c7b3cd6a9548adc5a5635161031c5a4666d18b792b5d482c0/libarchive/libarchive]<https://github.com/libarchive/libarchive>
GitHub - libarchive/libarchive: Multi-format archive and compression library<https://github.com/libarchive/libarchive>
Multi-format archive and compression library. Contribute to libarchive/libarchive development by creating an account on GitHub.
github.com

________________________________
发件人: Ivan Ivanenko ***@***.***>
发送时间: 2023年4月18日 23:27
收件人: foobnix/LibreraReader ***@***.***>
抄送: Krasnaya Ploshchad’ ***@***.***>; Author ***@***.***>
主题: Re: [foobnix/LibreraReader] A possible solution for CBR (Issue #1097)


Unarr has licence that not compatible with fdroid rules

―
