### ISSUE TITLE
F-Droid Offers Broken Librera 8.9.5

### ISSUE THREAD

**Issue by bigboipete** [foobnix/LibreraReader#1105]
My F-Droid App (v1.16.3) offered me Librera 8.9.5 (as of Apr 27th) today. After the update the app crashed at every start. I uninstalled it for now.

I started looking around and found this to be quite odd, as neither here nor at the f-droid.org website Librera version 8.9.5 is promoted. On librera.mobi it's 8.8.104 and on F-Droid.org website it's 8.8.107. So the topic is a bit inconsistent in general.

Could you please clarify the release history and current version of LibreraReader?
![Screenshot_F-Droid_20230428-110855](https://user-images.githubusercontent.com/38537584/235107849-fef1a9a8-6702-42cd-af85-05add4e59251.png)

**Comment by bigboipete** [comment]
A few minutes ago F-Droid website also updated the offered version to 8.9.5., which is unusable on my AOSP 8.1. (see #1106).

**Comment by rzasharifi** [comment]
here is the log:

java.lang.UnsatisfiedLinkError: No implementation found for int org.ebookdroid.droids.mupdf.codec.MuPdfDocument.getMupdfVersion() (tried Java_org_ebookdroid_droids_mupdf_codec_MuPdfDocument_getMupdfVersion and Java_org_ebookdroid_droids_mupdf_codec_MuPdfDocument_getMupdfVersion__)
	at org.ebookdroid.droids.mupdf.codec.MuPdfDocument.getMupdfVersion(Native Method)
	at com.foobnix.pdf.info.AppsConfig.<clinit>(AppsConfig.java:51)
	at com.foobnix.pdf.info.AppsConfig.loadEngine(Unknown Source:0)
	at com.foobnix.LibreraApp.onCreate(LibreraApp.java:54)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1212)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7103)
	at android.app.ActivityThread.access$1600(ActivityThread.java:271)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8309)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by resoli** [comment]
Same here (LOS 18.1)

**Comment by riveravaldez** [comment]
Hi, as commented in #1106 I'm also having this issue.
Please let me know if there's any useful info I could provide to help solve it.
Thanks a lot!

**Comment by ikanakova** [comment]
Same here (One UI 5.1 - Android 13)

**Comment by ArijitBh** [comment]
Same here. Moto g31- android 12

**Comment by SHMAUS-Carter** [comment]
Crashes on my Hisense touch e-reader as well

**Comment by CaitlinMkaKatie** [comment]
G'morn' to ye all
can confirm this issue for my Samsung/Android 11 too.
 Was so bad that my mobile recommended sending the App to deepStandBy by hand
uninstalled the 8.9.x version of 27th April and downgraded and this version the x.107 is working properly.

**Comment by bigboipete** [comment]
Before the 8.9.5. upgrade I had 8.8.104 installed, which is also still mentioned on the [Lirera Website](https://librera.mobi/what-is-new/) and was offered by F-Droid before.

If you look at F-Droid now, there are only three versions available. The broken 8.9.5. as suggested, the 8.8.107, which isn't promoted at [Lirera Website](https://librera.mobi/what-is-new/) and an 8.8.89 which is said to be added on Apr 15th 2023. Version 8.8.104 isn't available anymore.

This all looks very odd to me, as my recent 8.8.104 was definitely offered earlier. I will keep the app uninstalled until we get a complete picture here, which I haven't for now.

**Comment by MathCMN** [comment]
Can confirm the issue on my Oppo Find X2 Neo on ColorOS 12.1 | Android12.
Same as many people here, I had to downgraded on previous version. Hopefully it doesn't clear my parameters (files and current readings), only remove the widget.

**Comment by ferromint** [comment]
Salvation seems to be on the way:
https://gitlab.com/fdroid/fdroiddata/-/commit/59c37c650cbb870840057d67d05ec5a443c280cb

[rant]
Since when did GitHub users stop to bother looking at the titles of the few latest issues just below this one before creating another duplicate? Not to speak of using the search function which is not even necessary in this case. Now there are **3!** additional / duplicate issues #1106, #1107, #1109 as @resoli already [stated](https://github.com/foobnix/LibreraReader/issues/1109#issuecomment-1528971351) 🤦‍♂️
[/rant]

**Comment by riveravaldez** [comment]
Hi, in my case problem seems fixed on F-Droid version `8.9.12-fdroid (5458)` added on 2023-05-02. Hope it's the same for everybody. Regards!
