### ISSUE TITLE
Crashes at start after upgrade

### ISSUE THREAD

**Issue by riveravaldez** [foobnix/LibreraReader#1106]
Hi, thanks a lot for this amazing app.
I've just updated Librera through F-Droid to version 8.9.5-fdroid on LineageOS 17.1-20220211-NIGHTLY-surnia (Android 10) on a Moto E LTE. Now the app crashes trying to start, can't use it a tall, also can't downgrade it.
Let me know if I can give any useful information.
Kind regards!

**Comment by bigboipete** [comment]
See #1105

**Comment by riveravaldez** [comment]
@bigboipete Thanks!

**Comment by SHMAUS-Carter** [comment]
> Hi, thanks a lot for this amazing app. I've just updated Librera through F-Droid to version 8.9.5-fdroid on LineageOS 17.1-20220211-NIGHTLY-surnia (Android 10) on a Moto E LTE. Now the app crashes trying to start, can't use it a tall, also can't downgrade it. Let me know if I can give any useful information. Kind regards!

To downgrade simply uninstall and install an older version you cannot install an older version on top of a newer version as of recent Android versions. You're reading history and what not will survive an uninstall as they are stored inside the folder on your SD card but if you really that concerned about them do yourself a favor and zip up the folder just in case so you have a backup

**Comment by riveravaldez** [comment]
Problem seems fixed on F-Droid version `8.9.12-fdroid (5458)` added on 2023-05-02. I'm closing this, but let me know if I shouldn't, please.
Kind regards and thanks a lot!
