### ISSUE TITLE
Unable to switch orientation in recent releases

### ISSUE THREAD

**Issue by mhdna** [foobnix/LibreraReader#1110]
Hi,

 I'm not able to switch orientation in any way at all.  I've tested that on the latest 8.9.12-fdroid release, the 8.9.5-fdroid release, as well as the 8.8.5-fdroid release.

Eventually, I downgraded it to 8.6.46-fdroid, and it did work.

System: Android 8.0.0

Thanks in advance.

**Comment by Teashrock** [comment]
I confirm this, it's the same on my Samsung Galaxy S6 Lite.
