### ISSUE TITLE
Identify Librera somehow in it's user agent string

### ISSUE THREAD

**Issue by dunxd** [foobnix/LibreraReader#1128]
Librera currently supplies [a very generic User Agent value](https://github.com/foobnix/LibreraReader/blob/master/app/src/main/java/com/foobnix/opds/OPDS.java#L57) when requesting resources. I am working on a library server that automatically redirects detected OPDS clients to the OPDS feed, but cannot with Librera as I have not figured out a way to identify it. 

If the USER_AGENT string sent when accessing the html interface of my library included "Librera" it would be simple to do this. I already have it working that way for Moon+ and other readers, but Librera is better and the one I recommend to users.

In case you are interested [my library server ](https://github.com/dunxd/HomeAssistantAddons/tree/main/COPS) is a fork of COPS built for hosting on Home Assistant.

**Comment by foobnix** [comment]
fixed

**Comment by dunxd** [comment]
That's great.  I've updated my library server to look for `Librera` in the user agent, so I shoild see detection with the next Librera update on the Play store.

**Comment by foobnix** [comment]
you can test with beta.librera.mobi

**Comment by dunxd** [comment]
Works perfectly for Librera Pro-8.9.19-uni.apk - I guess the non-Pro Fdroid version doesn't include Network libraries?
