### ISSUE TITLE
Font size for each file

### ISSUE THREAD

**Issue by ijustknow** [foobnix/LibreraReader#113]
Now the font and the size are global, can it be one variable for each file?

**Comment by foobnix** [comment]
It's not possible (not implemented)

**Comment by ijustknow** [comment]
I migrated from a Chinese app called DUOKAN, which has the function, and can handle very well for scanned pdf (reflow is very powerful, I know it uses OCR). I left because it has too many ads.
If you want, i can share you the apk, but source code is not open.

**Comment by foobnix** [comment]
I can add font size for each book in the next update. I can implement it soon.
Please send me DUOKAN app to check,
Thank you.

**Comment by ijustknow** [comment]
It is a pity DUOKAN has no English interface, but the UI is very simple, I think you can try its functions well.

http://www.duokan.com/product
please use “Android 下载” link

**Comment by foobnix** [comment]
Thank you for remind me, I will start working on it this week.

**Comment by foobnix** [comment]
I decide not to make font size for each book but! in new [beta.librera.mobi](url) you can switch between profiles and make differnt font size for books in profiles.
