### ISSUE TITLE
Support SAF document provider

### ISSUE THREAD

**Issue by antrmn** [foobnix/LibreraReader#1142]
Currently, i get "Incorrect Value" error if I try to add a folder from a document provider (E.g. Nextcloud).

I think it would be a nice addition to implement access to SAF document providers. This way, it would be possible to use a cloud storage in a transparent way

**Comment by foobnix** [comment]
Please try to add Nextcloud path as a resource
https://librera.mobi/faq/how-to-delete-file-from-external-sd-card/

What Nextcloud application do you use?

**Comment by foobnix** [comment]
By the documentation, not all apps support TREE navigation (For example official GDrive), only single file selection. So your Nexcloud client may not support this feature.

**Comment by antrmn** [comment]
I believe this issue has not been discussed enough before being closed. 

Selecting a NextCloud directory for both profile or libraries results in an error. SAF support is there, but could be improved I guess.
