### ISSUE TITLE
[Feature Request] citation mode

### ISSUE THREAD

**Issue by thejohnd0e** [foobnix/LibreraReader#1146]
Is it possible to add citation functionality - when "share" is used add the author's name and book title at the bottom? Tnx.

**Comment by foobnix** [comment]
Could you please add some sample?

**Comment by thejohnd0e** [comment]
Ok,  so we copy the text, then select "share" in the context menu, then send the text to notes, for example.
We got the text from the book in the notes, but it was be good to have the author's name and book title at the bottom of the note. Otherwise it's hard to find the source of the quote.

![Screenshot_2023-08-17-05-44-28-277_com foobnix pro pdf reader](https://github.com/foobnix/LibreraReader/assets/115493464/8e6b69a9-bb10-465c-b410-a36226d0a8eb)
kkk

![Screenshot_2023-08-17-05-45-53-289_com miui notes-edit](https://github.com/foobnix/LibreraReader/assets/115493464/0cf3b809-8929-44b0-ae43-a7f5e8997263)

**Comment by foobnix** [comment]
fixed in beta.librera.mobi

**Comment by thejohnd0e** [comment]
> beta.librera.mobi

thank you so much, works great!
