### ISSUE TITLE
[feature request] option to keep book appearance locked by default in reader

### ISSUE THREAD

**Issue by d3rpd3rpd3rp** [foobnix/LibreraReader#1150]
I think Librera is the true successor to EBookDroid for the best overall Android reader. However, one issue that I have with it is the apparent lack of option to keep the book view locked by default upon opening (as indicated by the lock icon at the bottom-right hand of the screen). This makes it so that I must manually change the default from unlocked to locked for every book that I wish to prevent from being accidentally dragged/shifted away from its initial position while reading (which is true for +99% of them). At minimum, please provide a library-wide option to open books in locked mode by default, this would prevent much extra work for people like me. Keep up the great work Librera Devs, and thanks!

**Comment by chemicalcain** [comment]
This has existed for a while, but it's easy to miss since it's in Library Settings. Below the theme selection and brightness slider, there's a checkbox for "Remember reading mode." Beside it, you'll see the selected mode and a settings cog. Inside that settings dialog, you can set the default reading mode for different extensions using a comma delimited list. I personally have all my epubs open in Book mode (paginated) and all my PDFs in Scroll mode.

Scroll lock memory should be made as a separate post for issue tracking. I think it works but can't verify at the moment whether I've futzed with a different setting.

**Comment by d3rpd3rpd3rp** [comment]
> This has existed for a while, but it's easy to miss since it's in Library Settings. Below the theme selection and brightness slider, there's a checkbox for "Remember reading mode."
 
Yes I have that enabled to open DJVU and PDF files in book mode, however they open unlocked by default. I still have to manually lock every PDF/DJVU to prevent it from being accidentally moved around in the reader display.

**Comment by chemicalcain** [comment]
Oh, I misunderstood. Thanks fkr clarifying the issue. Yes, I can confirm I have to manually toggle the padlock for each file, though the setting is remembered for each file once set. A settings toggle to start locked by default would be nice. 8.9.20-fdroid

**Comment by brezelman** [comment]
What's the advantage of the unlocked state even? Does anyone want to see white space around pages and drag the pages out of view?

**Comment by d3rpd3rpd3rp** [comment]
> What's the advantage of the unlocked state even? Does anyone want to see white space around pages and drag the pages out of view?

I wondered that myself. The only advantage I can think of are perhaps with large comic books, to scroll frame by frame.

**Comment by d3rpd3rpd3rp** [comment]
> What's the advantage of the unlocked state even? Does anyone want to see white space around pages and drag the pages out of view?

I wondered that myself. The only advantage I can think of are perhaps with large comic books, to scroll manually frame by frame.

**Comment by chemicalcain** [comment]
> What's the advantage of the unlocked state even? Does anyone want to see white space around pages and drag the pages out of view?

Unlocked state is genuinely helpful for any PDF that isn't formatted as a single-column book. Comics, magazines with multiple columns, newspapers, etc. The lock/unlock feature is useful, but it's defaulting to the lesser used behavior of unlocked, while it would flow better to default to locked.

**Comment by d3rpd3rpd3rp** [comment]
I was just looking at the "Advanced Settings" under "Preferences" and noticed a new option "Lock page in place". After enabling this option, all books now open as locked, exactly the feature I was looking for! I haven't seen it listed in the changelog, but perhaps I overlooked it. Thank you Librera devs @foobnix for listening to users!

**Comment by Yolakalemowa** [comment]
> I was just looking at the "Advanced Settings" under "Preferences" and noticed a new option "Lock page in place". After enabling this option, all books now open as locked, exactly the feature I was looking for! I haven't seen it listed in the changelog, but perhaps I overlooked it. Thank you Librera devs [@foobnix](https://github.com/foobnix) for listening to users!

Hello friend, where is this setting? I can't find "advancd settings" in preferences. 

thank you (I'm on version 9.0.5)

EDIT: oh looks like it's in the preferences menu when you're viewing it from inside a document, not global settings. That should probably be fixed. But anyway. nvm thanks
