### ISSUE TITLE
[feature request] manual screen rotation + lock

### ISSUE THREAD

**Issue by enihcam** [foobnix/LibreraReader#1151]
i don't often turn on the screen auto-rotation because for most of the scenarios i stick with portrait (vertical). however, for video watching and book reading I'd love landscape (horizontal) due to the limited size of the screen.

video player can be set to default to landscape (full screen), so I'd eagerly ask for the same feature for book reading via librera.

thanks.

**Comment by nobkd** [comment]
You can set LibreraReader to Landscape mode:

1. Open Hamburger Menu
2. General Settings
3. Orientation
4. Set to `Landscape`

<details>
<summary>Open to see Image Instructions</summary>

![LibreraScreenOrientationNote](https://github.com/foobnix/LibreraReader/assets/44443899/663e3cfc-b8af-41e2-a709-e81063fae33f)

</details>

And if you want to set the app to `Fullscreen`, that's the option `Screen` also in general settings

**Comment by enihcam** [comment]
thx.
