### ISSUE TITLE
Make TTS control buttons more contrast

### ISSUE THREAD

**Issue by Korb** [foobnix/LibreraReader#1152]
Currently, the blue buttons "Rewind", "Play / Pause", "Fast forward" and "Close" are displayed in color 0961ba, which is difficult to see on an AMOLED screen at maximum brightness, dark application theme, black background and in sunny weather. The same with the minimum brightness of the screen in almost complete darkness.

I suggest making these icons two-color, with contrasting borders, so that they are equally distinguishable in bright light, both in a light application theme and in a dark one.

![Make TTS control buttons more contrast](https://github.com/foobnix/LibreraReader/assets/3509797/61f0d80e-3024-4ce2-92cf-66cd583a709e)

**Comment by foobnix** [comment]
please check beta.librera.mobi, you can also change the accent color of the buttons
<img width="524" alt="Screenshot 2023-09-26 at 12 14 07" src="https://github.com/foobnix/LibreraReader/assets/432440/d93490a6-761a-4614-bfe8-160bf835193c">

<img width="524" alt="Screenshot 2023-09-26 at 12 15 00" src="https://github.com/foobnix/LibreraReader/assets/432440/d4465aed-dd48-4996-a847-e6bc2a40c99c">

**Comment by foobnix** [comment]
<img width="524" alt="Screenshot 2023-09-26 at 12 18 27" src="https://github.com/foobnix/LibreraReader/assets/432440/aed21e47-d8ec-4243-93d1-4a9341bca16f">

**Comment by Korb** [comment]
> please check beta.librera.mobi, you can also change the accent color of the buttons

Are these settings still only available in the beta version of the app? Because in the latest version 8.9.60 available on [F-Droid](https://f-droid.org/packages/com.foobnix.pro.pdf.reader/), only the “Reading Settings”, “Advanced Settings” and “Status Bar” sections are displayed in “Preferences”.
