### ISSUE TITLE
Grid view grouped by folders

### ISSUE THREAD

**Issue by TheHardew** [foobnix/LibreraReader#1157]
When viewing folders it's only possible to view a list of folders.
Then, inside the folder you can view all the different covers of the books.
Instead, you could show a grid where each folder would be represented by the cover of the first book in this folder (or maybe the first unread book).

The problem with the current grid view is that it's difficult to find the book I want, among hundreds.
And the problem with the list view is that it's slow to use, looking at covers is much faster.

You could look at apps like tachiyomi for how it would be used:

![image](https://github.com/foobnix/LibreraReader/assets/7374061/1282226c-0582-41bd-8131-2888bad8a043)

**Comment by foobnix** [comment]
Please try **Folder** view in the Library, you can preview all books inside it
<img width="584" alt="Screenshot 2023-09-18 at 17 07 13" src="https://github.com/foobnix/LibreraReader/assets/432440/e5e97a8d-11d6-420d-93d3-aecc0dde0d55">

**Comment by TheHardew** [comment]
That shows all the books in the folder, I mean something that would show only 1 book per folder. After clicking on the book cover it would go inside the folder and show all the books in it.

**Comment by TheHardew** [comment]
That would be better than it is now I guess, but the images could be small this way. I was hoping for an option that works similar to the already existing grid/book cover options

**Comment by TheHardew** [comment]
Here is an example: https://demo.komga.org/libraries/all/series
log in with demo@komga.org password komga-demo

**Comment by foobnix** [comment]
please check beta
<img width="531" alt="Screenshot 2023-09-19 at 16 36 47" src="https://github.com/foobnix/LibreraReader/assets/432440/9ed804e0-0310-40ed-a824-fe93fb8c0c52">

**Comment by TheHardew** [comment]
Thank you
