### ISSUE TITLE
Highlighting inital letters fixes

### ISSUE THREAD

**Issue by TheHardew** [foobnix/LibreraReader#1160]
Thank you very much for providing this option in Librera!
There are just some slight adjustments that could hopefully be made.
So you can download the bionic reading app on the phone and play around with how it works, to see how it's implemented by the creators of the algorithm. Here are the main differences:

1. In words with apostrophes (whether ' or the Unicode \&#8217; &#8217; RIGHT SINGLE QUOTATION MARK) the part before the apostrophe should be treated as a single word  
e.g. don't -> <b>d</b>on't 
so take only don as a 3 letter word and disregard 't
2. In bionic reading you can choose the size of the highlighting. There are 5 options and reverse engineering them has been a little difficult, but I think it would be enough to provide the following:
    - words 1-3 letters long have only the first letter highlighted
    - words 4 letters long have 2 letters highlighted
    - longer words have round(A * length) letters highlighted, where A is a float provided by the user

**Comment by foobnix** [comment]
I see the bionic algorithm is a very different  on web and in the application
<img width="1382" alt="Screenshot 2023-09-18 at 12 35 43" src="https://github.com/foobnix/LibreraReader/assets/432440/0feb3364-27e8-4e48-b13a-a3ba78a36a89">

**Comment by foobnix** [comment]
please check new beta

**Comment by TheHardew** [comment]
that's the document I based my suggestions on: 
![](https://user-images.githubusercontent.com/39113159/169700493-8d433cf2-4a84-4757-a730-721365bb9188.png)

It sadly does not say anything about the apostrophe, since it uses german as the example
Playing around, maybe the right single quotation mark should be treated the same as an apostrophe then?
That's what my books use and currently it is displayed this way:
don’t -> <b>d</b>on’<b>t</b>
while it matches the web version it does not make much sense, since the function of that character is the same as that of an apostrophe

You can also see that they allow you to change the size of the fixation, and that would be helpful:
![image](https://github.com/foobnix/LibreraReader/assets/7374061/d2696a4b-eb3f-4d1c-bb28-579d0efe1cf9)

**Comment by TheHardew** [comment]
So I believe the new beta disregards the part after the apostrophe.
While now I'm not sure which version would be 'correct', that or using the whole word's length, I think it looks good, much better than treating them as 2 words, thank you very much

**Comment by foobnix** [comment]
please check beta 8.9.35 , you can send me the .txt and screenshots for check and for fix
<img width="1419" alt="Screenshot 2023-09-18 at 15 04 01" src="https://github.com/foobnix/LibreraReader/assets/432440/8029eadc-0dd3-468a-b04b-828dc6c0dc21">

**Comment by TheHardew** [comment]
Perfect, thank you!
