### ISSUE TITLE
Hardcoded ndk path?

### ISSUE THREAD

**Issue by TheHardew** [foobnix/LibreraReader#1161]
I believe in `link_to_mupdf_1.23.3.sh` the path to ndk is hard coded. And so is the version.
Running this script did not build `libMuPDF.so` for me which resulted in a crashing binary.
So it should try to find it and exit with a message and a non zero status when it can't.

**Comment by TheHardew** [comment]
My ndk is in /opt/android-ndk

**Comment by foobnix** [comment]
please modify as you want, I need the old NDK for mupdf 1.11 and the new NDK for the PRO version
