### ISSUE TITLE
Unable to change checkbox/icon/slider colors

### ISSUE THREAD

**Issue by TheHardew** [foobnix/LibreraReader#1162]
All the checkboxes/icons/sliders have the default teal color and I don't think it's possible to change that?

**Comment by foobnix** [comment]
Please add the screenshot

**Comment by TheHardew** [comment]
![Screenshot_20230918_161440.jpg](https://github.com/foobnix/LibreraReader/assets/7374061/f3b6a253-65a0-40d5-9384-fe8d1a9fed22)

They are teal colored, I'd like to change that

**Comment by foobnix** [comment]
fixed in new beta.librera.mobi
<img width="584" alt="Screenshot 2023-09-19 at 11 13 24" src="https://github.com/foobnix/LibreraReader/assets/432440/af7b879c-d2c8-48a4-bf8c-b0d214d0fa8e">

**Comment by foobnix** [comment]
+ SeekBar 
<img width="531" alt="Screenshot 2023-09-19 at 11 29 32" src="https://github.com/foobnix/LibreraReader/assets/432440/8de52136-06fc-439a-96d9-6ed6ca425b62">

**Comment by TheHardew** [comment]
Looks great, but would it be also possible to change the icon color? The cogwheel, the plus, the minus and so on

And maybe change the name "link color", since it now does more than only links?. Maybe "accent color"?
https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color

**Comment by foobnix** [comment]
Added
<img width="493" alt="Screenshot 2023-09-20 at 11 09 09" src="https://github.com/foobnix/LibreraReader/assets/432440/e25fa138-92dc-4fda-8b1b-fca6395950ae">
<img width="493" alt="Screenshot 2023-09-20 at 11 08 47" src="https://github.com/foobnix/LibreraReader/assets/432440/c45719d5-a125-4308-8637-4e7e49a13a35">

**Comment by TheHardew** [comment]
Here some  icons are still teal and the librera icon is all just one color:
![Screenshot_20230920_125510](https://github.com/foobnix/LibreraReader/assets/7374061/645c38f3-90a7-4042-a8af-651261859f83)

Here, similarly some icons are not displayed properly, the ones with the yellow border.
The one with the green one I think should just be left as white? 
![Screenshot_20230920_125500](https://github.com/foobnix/LibreraReader/assets/7374061/ec6e9ded-5b3e-49a1-a07a-06773bd0f79d)

Also, I found a few more locations, when the color is not applied properly:
![Screenshot_20230920_130915](https://github.com/foobnix/LibreraReader/assets/7374061/2be2b03c-b26e-48de-acac-5d37e2f29a8f)
![Screenshot_20230920_131045](https://github.com/foobnix/LibreraReader/assets/7374061/67b255b7-d35d-4fd1-b585-901515f50916)
![Screenshot_20230920_131107](https://github.com/foobnix/LibreraReader/assets/7374061/ae9aa940-1e74-4dd4-aec3-6ce8001d13d9)
![Screenshot_20230920_131111](https://github.com/foobnix/LibreraReader/assets/7374061/1c02e76a-b914-4c0c-95b0-23833e761e7a)
