### ISSUE TITLE
How to share text without the original author and "quotes" around the text

### ISSUE THREAD

**Issue by nyanikoding** [foobnix/LibreraReader#1164]
I wanted to be able to share some text from an ebook and put it onto Anki. But it always brings up the author, and "quotes" around the text.

How do I change this to be just text without any decorations around it?

**Comment by foobnix** [comment]
Please find in new beta.librera.mobi
<img width="584" alt="Screenshot 2023-09-19 at 10 57 15" src="https://github.com/foobnix/LibreraReader/assets/432440/1ac5fb6d-227c-42fe-9252-4bc8c1b58422">
