### ISSUE TITLE
English is not listed as an option language when the system default language is set to something different

### ISSUE THREAD

**Issue by Mhandis** [foobnix/LibreraReader#1166]
When the android system language is set to something other than English (Kiswahili in my case) the list of optional supported languages does not include English.
![librera2](https://github.com/foobnix/LibreraReader/assets/48302311/8bc33d6d-d721-42e8-ba73-caf3c5661ac1)
![librera1](https://github.com/foobnix/LibreraReader/assets/48302311/1096f210-eab6-4ae4-933d-d36839cd0674)

**Comment by foobnix** [comment]
fixed in beta.librera.mobi
