### ISSUE TITLE
Option to see Epub3 page number (similar to moon+ readed)

### ISSUE THREAD

**Issue by Ovi329** [foobnix/LibreraReader#1197]
Moon+ reader has added this option on their latest 8.6 update
![Screenshot_20231130-005607~2](https://github.com/foobnix/LibreraReader/assets/139252934/258418ef-8d03-4711-a470-d91a2ad71f66)
It adds the ability to see the the page breaks/page numbers which is embedded in the epub3 file. (2nd picture)
![Screenshot_20231130-004807~2](https://github.com/foobnix/LibreraReader/assets/139252934/8d249a5f-7716-4175-8e13-e8df216e135a)
Similar feature should be added to librera too

**Comment by foobnix** [comment]
Could you please send some epub3 book sample with pages

**Comment by Ovi329** [comment]
[epub3.zip](https://github.com/foobnix/LibreraReader/files/13505326/epub3.zip)

**Comment by foobnix** [comment]
Please find this in beta.librera.mobi
you can also configure "page N" style by custom CSS for exmpaple pn {color:red}
<img width="627" alt="Screenshot 2023-11-30 at 12 47 52" src="https://github.com/foobnix/LibreraReader/assets/432440/89c2347d-6ddf-48e2-9d69-386ceaba1ba6">
<img width="627" alt="Screenshot 2023-11-30 at 12 47 11" src="https://github.com/foobnix/LibreraReader/assets/432440/7b6d83dc-8554-45d3-aa1d-1fa8d8c276ef">
<img width="627" alt="Screenshot 2023-11-30 at 12 40 00" src="https://github.com/foobnix/LibreraReader/assets/432440/72029184-22d7-437c-abc3-0ab32617d3c7">

**Comment by Ovi329** [comment]
Wow, that was pretty quick. Other open source projects take weeks to months to solve a single issue and you did it in like 15 hours. Thanks. Looks neat btw. 
![Screenshot_20231130-170110](https://github.com/foobnix/LibreraReader/assets/139252934/9f69b52f-596f-495a-94e2-fbb461da0f91)

**Comment by foobnix** [comment]
it actually took 3 hours :)
Do you think it is necessary to navigate through epab3 pages to quickly go for example "page 55"

**Comment by foobnix** [comment]
Please find epub3 pages in outline
<img width="462" alt="Screenshot 2023-11-30 at 14 53 40" src="https://github.com/foobnix/LibreraReader/assets/432440/b24b8940-1af0-4e54-a872-6d5c36aa1c70">

**Comment by Ovi329** [comment]
Page outlines work with a happy death but not the fall apparently 
![Screenshot_20231130-201036](https://github.com/foobnix/LibreraReader/assets/139252934/9a7f87a3-8e1b-4b5b-9589-0769c9611dae)

**Comment by foobnix** [comment]
>"Page outlines work with a happy death but not the fall apparently" 
Can't clearly understand the issue.

**Comment by Ovi329** [comment]
The page outlines work on the book "A happy death" but doesn't work for "The Fall"
A happy death:
![Screenshot_20231130-201036~2](https://github.com/foobnix/LibreraReader/assets/139252934/7f30b149-5cfe-4514-8e52-893287a7b6b9)
The fall:
![Screenshot_20231201-023024~2](https://github.com/foobnix/LibreraReader/assets/139252934/cec68a67-32fa-4ba3-a89f-864ca930f513)

**Comment by foobnix** [comment]
Could you try to increase font size +1, i think this is old table context cache

**Comment by TheHardew** [comment]
There's already the "go to page" feature. Is there a need for a second one?

![Screenshot_20231204_140612](https://github.com/foobnix/LibreraReader/assets/7374061/97c4decd-5ad3-4a54-9e68-1019de000de6)

 It's the 3rd button from the left on the bottom.

**Comment by TheHardew** [comment]
I tried the test file in this thread and it does not open; "Unexpected error has occured" in both the beta and the stable version.

I also tried a few books from https://idpf.github.io/epub3-samples/30/samples.html like "Georgia" which is supposed to include page style navigation, but I did not see that, whether in the table of contents, the "go to page" menu or inside the book text. I do have the option turned on.

**Comment by TheHardew** [comment]
I also tried to check adb, but neither `adb logcat | frg AndroidRuntime`, `adb logcat | frg librera` nor `adb logcat | frg foobnix` seem to contain anything useful. But I don't really know how to use logcat so maybe there is some other way you could suggest.

**Comment by TheHardew** [comment]
Android 13, samsung galaxy s21+, I've installed the Pro 8.9.88 arm64 before, but even with Fdroid 8.9.85 uni it does not work. crash.txt was not generated. The application does not crash if it helps, just the book does not open.

**Comment by TheHardew** [comment]
I'm stupid, I'm opening the zip as an epub...

**Comment by foobnix** [comment]
Strange, for me it works...

**Comment by TheHardew** [comment]
That does work. Clicking the link, then pressing on the 10th page does not.
