### ISSUE TITLE
Starting Text-To-Speech (TTS) on a new install crashes the app unless you open and start it from the full TTS menu

### ISSUE THREAD

**Issue by Nitrousoxide** [foobnix/LibreraReader#1201]
## Summary

With all the reinstalling I was doing for the ToC cache issue I noticed a TTS issue as well.  It will crash if you attempt to open start TTS the first time on an install if you don't do so using the full TTS menu.  I believe you may also need to switch the book as well?  Though I'm not entirely sure on that point.

## Steps to replicate:

1. Install the app.  It can be a totally fresh install or one which has previous user data.  I don't believe it matters, though with the presence of previous user data (and thus settings) you're more likely to be in "Accessibility mode" and thus have the TTS control always visible at the bottom.
2. Make sure the accessibility mode is on to always have the tts control active.
3. Open a book and hit the TTS control at the bottom.
4. Phone will vibrate then app will crash

I assume this is due to some first-run TTS settings not being present when the accessibility mode is used to activate the TTS and thus cause a crash.  Flipping books and then using the full TTS menu seems to fix it, and then you can return to the book where the crash occurred and use the accessibility mode TTS controls just fine.  Other files also don't require first opening the full TTS controls.

## Images to reference the controls I am talking about:
Accessibility Mode Controls:
![Screenshot_20231202-072524](https://github.com/foobnix/LibreraReader/assets/1363931/cf68ad4e-1baa-4dfc-8553-b2cd128be474)

Full TTS Controls:
![Screenshot_20231202-072555](https://github.com/foobnix/LibreraReader/assets/1363931/b91a9266-1013-421f-bf97-f83331dad14e)

**Comment by foobnix** [comment]
Please install the beta.librera.mobi app, it should be fixed

**Comment by Nitrousoxide** [comment]
Also here is a video of how I get the crash.

https://cloud.nitrogendioxide.xyz/s/mEgFsx4Xkx4i9yY
