### ISSUE TITLE
Feature Request: Goes to logical page when entering page number

### ISSUE THREAD

**Issue by gannaiju** [foobnix/LibreraReader#1213]
If there're foreword, preface before main text, we can re-paginate page according to the official website help page ([https://librera.mobi/faq/relative-page-numbers/](url)).

The problem is, we still cannot go to the logical page when we enter a page number, instead librera will lead you to the physical page before re-paginating. Is it possible to go to the logical page when entering a page number?

**Comment by TheHardew** [comment]
Have you seen #1197?

**Comment by gannaiju** [comment]
> Have you seen #1197?

I use Librera only to read PDF files, not EPUB or other file formats.
I test several PDF files, all failed, but goes to the first page instead.
(Android version 8.9.115, installed from F-Droid.)

**Comment by foobnix** [comment]
Sorry, I can't clearly understand the problem you have described

**Comment by TheHardew** [comment]
I believe they want the feature that's implemented for epub 3 to also be ported to pdf

https://answers.acrobatusers.com/why-sets-page-numbers-q42394.aspx

**Comment by TheHardew** [comment]
PDF can include a second set of page numbers. I guess it's for cases like books, where the first physical page starts with the introduction or dedications and the first logical page would be the content?

**Comment by gannaiju** [comment]
> I believe they want the feature that's implemented for epub 3 to also be ported to pdf
> 
> https://answers.acrobatusers.com/why-sets-page-numbers-q42394.aspx

**Comment by gannaiju** [comment]
> Sorry, I can't clearly understand the problem you have described



> Sorry, I can't clearly understand the problem you have described

Sorry for my ambiguous description. But just as @TheHardew said:
Physical  page number starts with foreword, preface etc, 
Logical page number starts with real contents.
In Librera, enter a page number doesn't go to the correct logical page though the PDF files are re-paginated.

**Comment by gannaiju** [comment]
> PDF can include a second set of page numbers. I guess it's for cases like books, where the first physical page starts with the introduction or dedications and the first logical page would be the content?

Yes.

**Comment by foobnix** [comment]
Now I understand
Just long click on page number then set number like on the page
![Screenshot_20231222_073958](https://github.com/foobnix/LibreraReader/assets/432440/4c080c84-ce43-4f6a-95db-02bda99511ac)

**Comment by foobnix** [comment]
https://librera.mobi/faq/relative-page-numbers/

**Comment by gannaiju** [comment]
> Now I understand Just long click on page number then set number like on the page ![Screenshot_20231222_073958](https://private-user-images.githubusercontent.com/432440/292383193-4c080c84-ce43-4f6a-95db-02bda99511ac.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2Mzc3MDksIm5iZiI6MTcwMzYzNzQwOSwicGF0aCI6Ii80MzI0NDAvMjkyMzgzMTkzLTRjMDgwYzg0LWNlNDMtNGY2YS05NWRiLTAyYmRhOTk1MTFhYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwMDM2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWY4MTQ4ZTZjNGNlZDljMWYzZmE5NjVhMGUwNmY1YTZmMjk4OGIzMWYyNDUxMGY1ZjlkNTBkYzhhMWNkOWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qiqiJzYnS6qkBHYQkRuBW-yk3r9Pt9is1btVMl91O64)

As the image you show, when you want to switch to Page 55, you must enter 75 because there're some pages before main texts (Because there're preface, foreword, table of contents, or other chapters or sections exist.) Can I go to Page 55 when just type 55?

**Comment by foobnix** [comment]
@gannaiju Thanks, fixed in new beta.librera.mobi
