### ISSUE TITLE
Chapter names showing path

### ISSUE THREAD

**Issue by Hate9** [foobnix/LibreraReader#1229]
I'm sure it's just a setting *somewhere* that I accidentally hit at some point, but this app's settings are inscrutable, so who knows where.
![Screenshot_20240109-233646](https://github.com/foobnix/LibreraReader/assets/4684153/fbb691d0-5162-4a5d-b888-a88630c725ac)
As you can see, the chapter name at the top and in the selector is displaying with the chapter path after it.

How do I disable this?

**Comment by ikanakova** [comment]
Fixed already, see #1225
