### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by natebragg** [foobnix/LibreraReader#1238]
For those of us who use a physical keyboard with our mobile device, it would be very helpful to support keyboard shortcuts for common features (e.g., CTRL+F for find, CTRL+O for open a file, that sort of thing).  As of now, I have to switch back and forth between the keyboard and the touch interface, which slows me down.

**Comment by foobnix** [comment]
There are some shortcuts implemented:
0  is Go To Page dialog
1-9 is go to page 1-9
M - hide show panels UI
F - align page
S - for search

**Comment by foobnix** [comment]
I will add some more in beta.librera.mobi
Please check 

L - Library (open file)
T - TTS
C - content 
B - bookmarks

**Comment by natebragg** [comment]
That sounds great!  Any chance you could map ESC to dismiss a dialog (e.g., the find dialog?)

**Comment by foobnix** [comment]
done
