### ISSUE TITLE
Don't remove dash before line break when selecting urls

### ISSUE THREAD

**Issue by xxxxme** [foobnix/LibreraReader#1252]
When the user clicks a url in a pdf, dashes before line breaks/line wraps should not be removed. In the example screenshot, the text rendered leads to the intended article, but the link when clicked does not.

![61c0b497-5684-465e-8347-b206160114bc png](https://github.com/foobnix/LibreraReader/assets/3073154/4ee67683-de37-4941-b3c8-733f61f15fa8)

(Screenshot only as I'm not allowed to share the entire pdf.)
Librera 8.9.158-fdroid-6018 on LineageOS 20

**Comment by foobnix** [comment]
fixed in new beta.librera.mobi
