### ISSUE TITLE
[bug] DOCX footnote linking doesn't work correctly

### ISSUE THREAD

**Issue by Korb** [foobnix/LibreraReader#1253]
When clicking on a footnote in a .docx document, the footnote text is not displayed. At the same time, when viewing the same document in LibreOffice Writer, the footnotes are correctly displayed in the footer, and clicking on them in the document text correctly takes the reader to the text of the footnote itself.

View of screen with footnote:
![Opened by LibreraReader 8 9 60  1](https://github.com/foobnix/LibreraReader/assets/3509797/f95ecbe6-b264-4b00-915e-213565bf615c)
Screen view right after taping on the footnote number:
![Opened by LibreraReader 8 9 60  2](https://github.com/foobnix/LibreraReader/assets/3509797/05bea9f4-de4e-4efe-a5e1-2b14a2e8da9d)
Screen view after clicking on the "Go to Page 1536" link:
![Opened by LibreraReader 8 9 60  3](https://github.com/foobnix/LibreraReader/assets/3509797/91b5a36b-d3e6-47ca-ad0c-1dc32e3b5a0e)
View of the same place in the document opened in LibreOffice:
![Opeed by LibreOffice Writer](https://github.com/foobnix/LibreraReader/assets/3509797/ca12a7c3-22a9-40b2-95fd-503e8cb4ff55)

Ideally, I would prefer to read the footnote in a pop-up window immediately after clicking on the footnote number in the text. To close the pop-up window, I should just click outside the pop-up window or click on the cross in the upper right corner of the pop-up window. This is how Librera Reader behaves in the case of footnotes in FP2 documents.

If this behavior cannot be implemented for some reason, it would be convenient, immediately after clicking on the footnote number, to move to the footnote text (separate from the texts of other footnotes), and see next to the footnote text a link to the original location of the document to continue reading.

[demobook.docx](https://github.com/foobnix/LibreraReader/files/14626424/demobook.docx)

Perhaps the nature of the error is the same as in #1114.

**Comment by foobnix** [comment]
Please try to find this book in Epub, docx is not a priority file format for Librera Reader

**Comment by Korb** [comment]
> foobnix closed this as completed on Mar 18, 2024

Perhaps this issue should have been closed `as not planned` ("won't fix, can't repro, stale")?
