### ISSUE TITLE
Change Librera Reader language by App languages system setting screen

### ISSUE THREAD

**Issue by Korb** [foobnix/LibreraReader#1255]
I suggest you consider changing the language of the application through a single control center for the languages of installed applications, available in the latest versions of Google Android. Read more about it in the article "[Change app language on your Android phone](https://support.google.com/android/answer/12395118)" of the official OS help. [Screenshot](https://drive.google.com/file/d/1rhT3cFpo8cpeLrXIPteFH-0202ks_IYy/view)

**Comment by foobnix** [comment]
I think if you choose System language in Librera then if you change the language as you mention - the app applies the Android phone language

**Comment by Korb** [comment]
@foobnix, forgive me, but I don’t understand how your answer relates to my proposal to use the mechanism for managing user application locales recommended by the OS developer?
