### ISSUE TITLE
Support jp2 image format

### ISSUE THREAD

**Issue by IceflowRE** [foobnix/LibreraReader#1267]
It would be cool to support the jp2 image format. especially for comic books. 
There are millions of jp2 books on archive.org, so there is a demand.

**Comment by foobnix** [comment]
could you please attache some book sample

**Comment by foobnix** [comment]
Librera shoud suppord jp2 format 
static const char *cbz_ext_list[] = {
	".bmp",
	".gif",
	".hdp",
	".j2k",
	".jb2",
	".jbig2",
	".jp2",
	".jpeg",
	".jpg",
	".jpx",
	".jxr",
	".pam",
	".pbm",
	".pgm",
	".pkm",
	".png",
	".pnm",
	".ppm",
	".tif",
	".tiff",
	".wdp",
	".webp",
	NULL
};

**Comment by IceflowRE** [comment]
[jp2_example_book.zip](https://github.com/foobnix/LibreraReader/files/14979183/jp2_example_book.zip)
There you go. Rename to `.cbz` (uploading files with ending `.cbz` is not allowed).

**Comment by foobnix** [comment]
It's works, I don't see any problems
<img width="510" alt="Screenshot 2024-04-15 at 16 01 54" src="https://github.com/foobnix/LibreraReader/assets/432440/cc0a3874-b447-4781-b7fd-5706f6d10fa4">
