### ISSUE TITLE
Phone status bar covers parts of UI

### ISSUE THREAD

**Issue by Silent-Hunter** [foobnix/LibreraReader#1320]
Using version 8.9.181-fdroid, I've noticed that the UI is displaying as if it's fullscreen, but the phone status bar and gesture bar are covering up part of the app, making it hard to see and non-functional. Setting the "screen" option to Fullscreen partially fixes it, but the bottom gesture bar stays. Setting it to Notched does nothing.

![Screenshot_20241101-102519](https://github.com/user-attachments/assets/8e50216f-2b22-42a8-9656-fe1f97b37ced)
![Screenshot_20241101-103120](https://github.com/user-attachments/assets/97f79468-d549-44b2-9646-b5b6318641a5)

**Comment by LiftedStarfish** [comment]
I'm having the same issue on a Pixel 8 with GrapheneOS

**Comment by Silent-Hunter** [comment]
Oh yeah, I'm using GrapheneOS (Android 15) on a Pixel 6.

**Comment by foobnix** [comment]
fixed in the 8.9.182
