### ISSUE TITLE
将 “what is new in beta 7.8.38 ”改为“what is new”,然后转移到“product beta 7.8.38”界面下面，能使界面更美观，工整。

### ISSUE THREAD

**Issue by rockmax001** [foobnix/LibreraReader#137]
“what is new in beta 7.8.38”应该从“preferences”界面下删除，转移到“product:beta 7.8.38”界面下，因为它是属于对产品的说明，并不属于阅读设置。仅保留“what is new”就可以了，后面的版本号应该被删除。因为版本号会随着更新而有长度变化，不利于界面美观。

**Comment by foobnix** [comment]
please write on english
