### ISSUE TITLE
 e-ink optimizations improvement

### ISSUE THREAD

**Issue by bobqj** [foobnix/LibreraReader#146]
I found Librera is not good to show the effect of small fonts with complex backgroud text pdf files,but Librera is good for big fonts and simple backgroud pdf.Onyx's Neo Reader v2.0 is perfected display the small fonts with complex backgroud text pdf files.Neo reader could change text bold level for 1 to 5,I wish Librera also has this function.Most important of all,for dense blocks of text pdf,onyx neo reader app don't need to change text bold and the display effects is very good,because it keep the original text effect,this function is very important for some technical books and textbooks.I wish Librera also have this function and become more better.

**Comment by foobnix** [comment]
It's hard to implement the same as on Neo Reader, you can adjust brightness and contrast in Librera to have the same effect.
