### ISSUE TITLE
Beta 7.9.43 : PDF links not followed.

### ISSUE THREAD

**Issue by Lysidas** [foobnix/LibreraReader#167]
Hello,

With the Beta 7.9.43, the links are not followed in PDF files. I'm using an ONYX Max2. Or, do I must use an other version ?

Thanks for your help. Best regards.

Lysidas.

**Comment by foobnix** [comment]
Please attache some PDF and screenshot with the problem

**Comment by Lysidas** [comment]
Hello,

The problem seem linked to the the "2 pages mode" for PDF and EPUB files. The 2 first screenshots are for the EPUB file.

You must save et rename the  first picture because it's an EPUB file renamed '*.epub.png' as the second which is a PDF file.

Thanks for your help.
Lysidas

/* EPUB and PDF file */
![l_esprit_des_lois_bpt6k56753429 epub](https://user-images.githubusercontent.com/40823310/42571253-df07d9be-8516-11e8-89a0-2be87c4a5bd4.png)
Direct link : https://gallica.bnf.fr/ark:/12148/bpt6k56753429?rk=21459;2
![developers-reference pdf](https://user-images.githubusercontent.com/40823310/42571326-196d48a0-8517-11e8-924d-64cd75ea786a.png)
Direct link : https://www.debian.org/doc/manuals/developers-reference/developers-reference.pdf

/* Screenshots */
![screenshot_20180708-232627](https://user-images.githubusercontent.com/40823310/42570690-00057182-8515-11e8-8461-2c1a164f6b7b.png)
![screenshot_20180708-232857](https://user-images.githubusercontent.com/40823310/42570701-0b92354e-8515-11e8-806d-ad7c0ea7f4fa.png)
![screenshot_20180708-233206](https://user-images.githubusercontent.com/40823310/42570703-0bcc9a68-8515-11e8-8bbe-27bc575365b3.png)
![screenshot_20180708-233617](https://user-images.githubusercontent.com/40823310/42570704-0c11f180-8515-11e8-8865-4dbc6d67099c.png)
![screenshot_20180708-233831_r](https://user-images.githubusercontent.com/40823310/42570705-0c4bb24e-8515-11e8-834c-27f18f83f199.png)
![screenshot_20180708-233959_r](https://user-images.githubusercontent.com/40823310/42570706-0c87c0ae-8515-11e8-8028-d8f5ed6f1ff5.png)

**Comment by foobnix** [comment]
Thank you for the information,
fixed in Beta ([beta.librera.mobi](url)) and also links now underlined

**Comment by Lysidas** [comment]
It's good without the crop function for EPUB and PDF. If the crop function is used, the 'underline' is moved.

For some EPUB, I have a box which is displayed. Sometimes I have only the reference of the note/link and also I've seen the possibility to jump a the note/link... I must check more EPUB files and find what file I can give you..

Something else, could you increase again the margins for EPUB, with the Max2 a value of 40 is very small. With a bigger value, we can expect to have the same aspect than a paper book.


![screenshot_20180712-074226_r](https://user-images.githubusercontent.com/40823310/42624283-55da7232-85c5-11e8-8a92-6d41512333dc.png)
![screenshot_20180712-074843_r](https://user-images.githubusercontent.com/40823310/42624284-561cab16-85c5-11e8-82e8-d3fa3c763e7c.png)
![screenshot_20180712-075800_r](https://user-images.githubusercontent.com/40823310/42624287-5653e554-85c5-11e8-9065-89a46e419bff.png)
![screenshot_20180712-080600_r](https://user-images.githubusercontent.com/40823310/42624288-568b4e2c-85c5-11e8-804b-c5d50c5aa6e0.png)
![screenshot_20180712-081156_r](https://user-images.githubusercontent.com/40823310/42624289-56bfa9e2-85c5-11e8-82dc-fcea8ed44dea.png)
![screenshot_20180712-081441_r](https://user-images.githubusercontent.com/40823310/42624291-570462a8-85c5-11e8-831b-81ee56b1399a.png)

**Comment by foobnix** [comment]
>If the crop function is used, the 'underline' is moved.
Unfortunately, links can't works with crop in current realization, need more time to implement this.

>For some EPUB, I have a box which is displayed. Sometimes I have only the reference of the note/link and also I've seen the possibility to jump a the note/link... 
yes, If the link has format like [1] or {1} it will open in the box, if other go to the corresponded page

>Something else, could you increase again the margins for EPUB, with the Max2 a value of 40 is very small. 
Will be 60 in new beta
