### ISSUE TITLE
Beta 7.9.96 : page changing and setting panel.

### ISSUE THREAD

**Issue by Lysidas** [foobnix/LibreraReader#182]
Hello Foobnix,

I try the Beta 7.9.96.

First (it's not a bug, but a request), could you increase the margins values (60) to 200 or more, because with the wide screen of the Onyx Max2 (13.3") the text for a EPUB file is to wide to have the same aspect than a paper book ?

I've notice the following things : 

- when the pages are rapidly turned, the message 'onLoadingStarted' is displayed and not the page number a each time. For a EPUB (novel), sometimes the page number is displayed, for my PDF technical book never;
- in the panel settings, only one change must be made at a time to be effective. If I change the font size or the font and I change of sub-menu in the panel settings with change anything in this sub-menu, when I close the panel settings, nothing is changed. But If I go in the list of recent books and I choose the same book, the modifications are done.

Thank you for your work.

**Comment by Lysidas** [comment]
On the same device, I have Librera-PRO-7.9.62-c612-d7-arm+arm64. I've installed the Beta 7.9.96 many weeks after the PRO version.

**Comment by foobnix** [comment]
>could you increase the margins values (60) to 200
In the next **beta** will be 2000

>when the pages are rapidly turned, the message 'onLoadingStarted' is displayed
Will be fixed in the next beta

>If I change the font size or the font and I change of sub-menu in the panel settings with change anything in this sub-menu
Yes, but in the last PRO should be warning to apply settings if you go to the sub-menu, I will check

**Comment by Lysidas** [comment]
Hello,
Thank you :+1: 

With the same file and this version, the message 'onLoadingStarted' is no more visible after fews tests.
