### ISSUE TITLE
Beta-7.9.97-c649 : EPUB for IT books.

### ISSUE THREAD

**Issue by Lysidas** [foobnix/LibreraReader#184]
With the Beta-7.9.97-c649 and IT books from the 'The Pragrmatic Programmers' (https://pragprog.com/), all code seems to be removed, there is only some long dashes.

But with the Librera-PRO-7.9.62-c612-d7-arm+arm64.apk the code is displayed.

With a book from O'Reilly (directly by in the O'Reilly 's store), the code is displayed.

**Comment by foobnix** [comment]
Could you please attache some book for testing?

**Comment by Lysidas** [comment]
Hello,
This an extract from a book, I've remove many things and kept only one chapter. The rendering is not good as the real book, but I have the same problem with this extract : the code is replaced by long dashes. So, the removed parts doesn't change anything.

[extract_file.epub.gz](https://github.com/foobnix/LibreraReader/files/2331604/extract_file.epub.gz)
