### ISSUE TITLE
Ручная установка обложки

### ISSUE THREAD

**Issue by OmlineEditor** [foobnix/LibreraReader#228]
Есть отсканированные книги в pdf форматах, когда на первых страницах не обложка, а реклама и прочий мусор. Ваше приложение берет первую страницу и думает что это обложка книги. К вашей программе притензий нет, это просто криво отсканировали книгу, с этим ничего не поделать.
Можно ли в меню программы добавить пункт: "использовать текущую страницу как обложку"
тогда я сама руками могу поправить обложку и сделать ее правильно. Также можно будет ставить на обложку что угодно из книги, это будет очень удобно.

**Comment by foobnix** [comment]
Я бы не хотел делать такой функционал.
Могу вам посоветовать найти PDF редактор и просто удалить ненужную страницу в книге.
В теории мне будет интереснее добавить такой редактор в читалку
