### ISSUE TITLE
[Upgrade] Do you plan to support additional Microsoft formats?

### ISSUE THREAD

**Issue by chihung93** [foobnix/LibreraReader#29]
Hello, I am very interested in this project.
Do you plan to support additional Microsoft formats?

**Comment by foobnix** [comment]
Hello
I want to support but I don't know good library that can read all of them.

1 лист. 2017 р. 04:56 "Sammy" <notifications@github.com> пише:

**Comment by chihung93** [comment]
What about this lib?
https://github.com/centic9/poi-on-android

Apache POI can be used for reading Microsoft formats.
Tks.

**Comment by foobnix** [comment]
Maybe but the problem poi has to big size (16mb) like the current app size.
Why don't you use Librera as Library organizer with other doc/x readers?

1 лист. 2017 р. 08:25 "Sammy" <notifications@github.com> пише:

**Comment by chihung93** [comment]
I'm using Librera for reading my book. It's awesome. ( 4 stars for this app )
I just wanna Librera better than other readers.
Sometimes I feel uncomfortable having to switch between Librera and another app.

**Comment by luo-chuan** [comment]
Please support doc and docx files. There are some apps support doc and docx, like AlReader, ReadEra, FBReader, but I am not sure whether they are open source. I want read all books in one app.

**Comment by foobnix** [comment]
I can't find doc-docx Small java or clang library for Android. I hope to add these formats in the future.

**Comment by Stele77** [comment]
I just saw in latest release doc+docx support is added! Great work! 
Just switched from Moon Reader and still testing, but i think i would stay with Libera and go for Pro version. 
I dont want to sound ungrateful, but may i ask if support for open document formats (odt) is also planned? As ODT is the open source format of Libre Office, it is quite widely used especially for Linux and Open Source users in general. 
Additionaly, as ODT is open source, shouldnt it be possible to support without too much work? As i am not a dev, so please understand if i am wrong and this is not so easy to do..
Thanks again!

**Comment by foobnix** [comment]
Odt is also already supported
