### ISSUE TITLE
GUI is too overloaded

### ISSUE THREAD

**Issue by rarecaller** [foobnix/LibreraReader#339]
Don't know if a lot of people would agree with me, but I think that Librera PRO interface is too crowded and sophisticated. 

I installed it last night from the F-Droid as a possible replacement for [Book Reader](https://fossdroid.com/a/book-reader.html), which looks very clean and friendly, but works somewhat laggy and unstable sometimes. Now I'm seeing the direct opposite picture with Librera PRO: excellent performance and confusing appearance.

**Suggestions:**

- Hide each settings category under its own submenu.
- Use a special submenu for all advanced settings. 
- Remove all toolbars in the reading mode in favor of the corner menu and minimize the number of customizable view options. (Currently it looks really scary.)
- Reduce the number of tabs enabled by default so they could fit on the screen at the first launch. (Just leave two or three.)
- Perform a revision of all features. Now it looks like a mess of everything that came to mind.

I really like how fast and smooth Librera PRO works with my ebooks and documents. Wish the interface would be matching.

**Comment by foobnix** [comment]
thank you for feedback.
Librera has an unique interface and this style many users like, you need some time to understand its concept :) Of course, you can contribute improvements.

Please post your ideas separately as an independent issues, add some screenshots and more info and then we can implement it.

**Comment by c704710** [comment]
The post sugested multiple solutions but only 1 issue; GUI is too overloaded.
I agree.

1 solution: Minimizable GUI
