### ISSUE TITLE
Network Catalog not remembering user/pass

### ISSUE THREAD

**Issue by Alacard** [foobnix/LibreraReader#342]
Network Catalog not remembering user/pass, when connecting to a opds server that require a user/pass, when you close the app and reopen it will as you to re-enter user/pass

Backend Server: Calibre-web (https://github.com/janeczku/calibre-web)

**Comment by foobnix** [comment]
Can't reproduce with my catalogs.
Please send a sample OPDS link with test user\pass to check

**Comment by Alacard** [comment]
Emailed you the info you needed

**Comment by foobnix** [comment]
fixed in beta
