### ISSUE TITLE
Hi. I found your project today while browsing the internet today. It is an incredible project and I am already putting it to use.

### ISSUE THREAD

**Issue by IntenselyMichell** [foobnix/LibreraReader#343]
Hi. I found your project today while browsing the internet today. It is an incredible project and I am already putting it to use. I praise the incredible work you have done so far. I want to contribute to your project by creating some copies. That's documents of the privacy policy. For the declaration of the privacy policy, this is very necessary for the cases in which the data collection is carried out. I do not think it collects user information when using the software. However, I realized that the application has full network capabilities and things like that always make people skeptical. A concise statement of the privacy policy will put an end to all that skepticism, generating more confidence and leaving things clear. This document could be modified later as many times as necessary, it is only a beginning, but it would cover the most relevant aspects of privacy. Let you know what you think about this.

**Comment by foobnix** [comment]
Hi, Thank you for feedback.
If you make a close you should modify the privacy policy to your requirements.
The app is collect nothing but third-party google ads and google firebase can store some info.
