### ISSUE TITLE
FB2 book opens cut

### ISSUE THREAD

**Issue by ildar** [foobnix/LibreraReader#345]
Couldn't find anything relevant in adb logcat.
The book with the issue: https://flibusta.is/b/337477
The book is showing just a small first part after a long opening delay.

**Comment by foobnix** [comment]
Please try beta.librera.mobi, I see this book correctly. You can also read epub version of this book.

**Comment by ildar** [comment]
Beta is unavailable in F-Droid. Are there plans for that?
Also I'm not sure it's "old versus new" problem. May it be the lack of RAM
problem (my phone has 2GB RAM). Though I never seen problems opening this
FB2 in FBReader and "Book Reader" (from F-Droid).
This idea came when once I opened it shew less then 4 chapters, another
time it shew more (maybe 5 or 7).

**Comment by ildar** [comment]
Just tried on Beta. The problem persists. Please reopen the issue.
