### ISSUE TITLE
Cover, title and author identical

### ISSUE THREAD

**Issue by heycrip** [foobnix/LibreraReader#352]
My library consists of about 10k titles but somehow Librera repeats the same author, title and cover over and over and over.
Tried on Beta 8.1.157 (play store) and on the PRO version (fdroid) on Android 5.1.1.

If I can give more info, logs or screenshots, let me know.

**Comment by heycrip** [comment]
![Screenshot_2019-06-17-13-34-08](https://user-images.githubusercontent.com/12774050/59613181-bf893f00-911e-11e9-8e2b-7e8cf06a4b1c.png)

**Comment by foobnix** [comment]
Please open file info dialog for the duplicate book to be sure it's not the different copy of one book in many places.
I see the process of library creation is not finished, what do you see after finish updating the library?

**Comment by foobnix** [comment]
Please check book paths in the book info dialog

**Comment by heycrip** [comment]
Sorry, posted a less than useful screenshot. This one should be better.

![Screenshot_2019-06-17-16-49-30](https://user-images.githubusercontent.com/12774050/59613955-180d0c00-9120-11e9-89e2-6002315d231b.png)

**Comment by foobnix** [comment]
Please check full paths


![Screenshot-2019-06-17-17-54-04](https://user-images.githubusercontent.com/432440/59614278-1562e480-9129-11e9-92ed-5457dba12100.png)

![Screenshot-2019-06-17-17-54-08](https://user-images.githubusercontent.com/432440/59614277-1562e480-9129-11e9-994d-9158838e7fb3.png)

![Screenshot-2019-06-17-17-54-14](https://user-images.githubusercontent.com/432440/59614276-1562e480-9129-11e9-81b8-b931b2c26eea.png)

**Comment by heycrip** [comment]
Yeah the file paths are different. 
I noticed they are all 0.00 bytes though, so something is wrong. I'll check it out.

**Comment by heycrip** [comment]
Okay, I've copied all the books again and removed the 0 byte files and this has resolved the issue.

**Comment by foobnix** [comment]
Very good news :)

**Comment by heycrip** [comment]
This has come up again on another device on non-zero byte files. This time the cover does show the correct book but otherwise all books have the same title and author and description. 
I'll add a screenshot from the device.

**Comment by heycrip** [comment]
![Screenshot_20190627-075012_Librera_PRO](https://user-images.githubusercontent.com/12774050/60240387-0d394080-98b1-11e9-990a-b08d9368a8ff.png)

(this one is from Librera PRO 8.1.170 on Android 9)

**Comment by foobnix** [comment]
Please install beta, I have added a fix to skip 0 size files

**Comment by heycrip** [comment]
See screenshot (posts crossed)

Tthere are around 10,000 files (epub, mobi, pdf) in a single folder, could that be an issue?

**Comment by foobnix** [comment]
I don't see any problem on the screenshot, book path name and cover are correct.
Just check
1) Update library without metadata (see screenshot)
2) Check for exist\absent file "metadata.opf" in the folder

![Screenshot-2019-06-27-09-50-55](https://user-images.githubusercontent.com/432440/60243538-1e8a4900-98c1-11e9-88f4-800b133b6dbf.png)

**Comment by heycrip** [comment]
> I don't see any problem on the screenshot, book path name and cover are correct.
> Just check
> 
> 1. Update library without metadata (see screenshot)
> 2. Check for exist\absent file "metadata.opf" in the folder
> 
> ![Screenshot-2019-06-27-09-50-55](https://user-images.githubusercontent.com/432440/60243538-1e8a4900-98c1-11e9-88f4-800b133b6dbf.png)

The author and title are incorrect in the screenshot. The cover and file path are correct, yes, which is how you can clearly see something is wrong. EVERY BOOK in my library has this author and title.

On the other device it was resolved, so it's not a device specific issue. 

What is the point of displaying file names? That will be a gigantic mess, won't it? Unless all the files are uniformly named (in my case they are not). Or is it for debug purposes?

**Comment by foobnix** [comment]
I really don't know why it may happen.

You can help me to find the issue, maybe you can add 2-3 books to some folder and then add only this folder to the library. if the problem will reproduce please send me these books.

I may assume some of the book can create an issue to freeze or crash something. but without this book I can't fix.

Please try to send me logcat log if you can

Thank you,
Ivan

**Comment by heycrip** [comment]
Yeah that makes sense.
On the other device, I put the books in separate folders and after that, the problem was resolved. I will try doing that on this device later and see what happens.

I'll also do your suggestion to see what happens with that. I'll let you know later.

**Comment by heycrip** [comment]
There was one *metadata.opf* file in the folder with the unsorted books.

Removed the metadata.opf file and rebuilt the library, this solves the issue.

**Comment by foobnix** [comment]
Thanks, I will fix this case
