### ISSUE TITLE
F-Droid version has jittery scrolling in Scroll Mode, only when dragging finger

### ISSUE THREAD

**Issue by opusforlife** [foobnix/LibreraReader#353]
While your finger is touching the screen, the scrolling is jittery. When you lift it and the rest of the fling animation takes place, the scrolling is smooth until it comes to a stop.

I turned Profile GPU Rendering on. And sure enough, the bars are consistently higher while dragging versus while flinging.

**Comment by foobnix** [comment]
Please check bt.librera.mobi or beta.librera.mobi final beta version.
Is it problem exists?
Please send the video for more information

**Comment by opusforlife** [comment]
Yes, it exists in the beta apk.
[ScreenRecord.mp4.zip](https://github.com/foobnix/LibreraReader/files/3307192/ScreenRecord.mp4.zip)

**Comment by opusforlife2** [comment]
Hi. The F-Droid version was finally updated, so I got to test it recently. The jitter has been reduced, but it hasn't gone away completely. I don't know how other apps do it, but for example, Markor renders text without any jitter when scrolling through large text files. Moon+ Reader from the Play Store, which I discarded in favour of Librera, could also scroll without any jitter.

**Comment by foobnix** [comment]
Scroll mode is based on old Eboodroid engine, need to rewrite it, maybe someday someone fix it.
