### ISSUE TITLE
code indentation is not respected

### ISSUE THREAD

**Issue by gaydenko** [foobnix/LibreraReader#359]
Hi!
Let's try this EPUB document: 
https://docs.spring.io/spring-boot/docs/current/reference/epub/spring-boot-reference.epub
As you can see, code (pre) fragments are broken: code indentation is not respected. I guess, nbsp, tabs and raw spaces are must all be equally respected in `pre`. At the case it seems tabs (09) are ignored.

**Comment by foobnix** [comment]
just install bt.librera.mobi and add custom CSS style
![Screenshot-2019-06-27-12-32-57](https://user-images.githubusercontent.com/432440/60255215-ff4ae600-98d7-11e9-97c3-7d95e3ddee0c.png)
![Screenshot-2019-06-27-12-32-16](https://user-images.githubusercontent.com/432440/60255216-ffe37c80-98d7-11e9-926c-628b33c8f411.png)

**Comment by gaydenko** [comment]
@foobnix The second image above shows indentations are not respected. Say, `private final AcmeProperties...` is not shifted to right.

**Comment by foobnix** [comment]
try with "User defined" styles
![Screenshot-2019-06-27-12-45-10](https://user-images.githubusercontent.com/432440/60256036-7cc32600-98d9-11e9-9f4c-306e9b78aebf.png)
![Screenshot-2019-06-27-12-45-00](https://user-images.githubusercontent.com/432440/60256037-7cc32600-98d9-11e9-8f18-efd365f58998.png)
![Screenshot-2019-06-27-12-44-52](https://user-images.githubusercontent.com/432440/60256039-7d5bbc80-98d9-11e9-83f5-5bc478e7fcf9.png)

**Comment by gaydenko** [comment]
Probably, there is some additional option influencing to indentation.

![Screenshot_20190627_134502_com foobnix pro pdf reader](https://user-images.githubusercontent.com/3740016/60260435-48a03300-98e2-11e9-9834-c8dbee5d0d70.jpg)

![Screenshot_20190627_134540_com foobnix pro pdf reader](https://user-images.githubusercontent.com/3740016/60260436-48a03300-98e2-11e9-823f-ed6892c375fd.jpg)

The last official pro is in use.

**Comment by gaydenko** [comment]
I have found replacing `pre-line` with `pre-wrap` does the trick. But the indentation is one symbol only, and it is too small.

**Comment by foobnix** [comment]
Nice work!
