### ISSUE TITLE
add table support

### ISSUE THREAD

**Issue by gaydenko** [foobnix/LibreraReader#360]
I mean tables looking as... tables :) That is with borders (and with an opportunity to keep font size as main text's one).

**Comment by foobnix** [comment]
tables did not support by mupdf, I hope they will add them in the future ...
Librera use mupdf for rendering pages

**Comment by mxmilkb** [comment]
I've commented on the apparently related MuPDF bug [here](https://bugs.ghostscript.com/show_bug.cgi?id=700013).
