### ISSUE TITLE
MuPDF 1.11 vulnerabilites

### ISSUE THREAD

**Issue by batzuli** [foobnix/LibreraReader#367]
Librera is using MuPDF 1.11 which has some vulnerabilites.
https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=mupdf
can you update the MuPDF version you use to the newest 1.15.1 version which closes the vulnerabilites?

**Comment by foobnix** [comment]
I see only 1.15.0 yes, I have idea to update to latest mupdf after release

**Comment by foobnix** [comment]
now you can build librerea with Mupdf 1.16.1 ../LibreraReader/Builder/link_to_mupdf_1.16.1.sh
