### ISSUE TITLE
Hyperlinks appear as regular text

### ISSUE THREAD

**Issue by rimugu** [foobnix/LibreraReader#376]
In most books with hyperliks I have seen the hyperlinks appear as regular text. They appear as link in fbreader android and windows calibre epub reader.
[Examples.zip](https://github.com/foobnix/LibreraReader/files/3502743/Examples.zip)

**Comment by rimugu** [comment]
The link do work, but are not distinctive

**Comment by foobnix** [comment]
Mupdf not support underline the text so hyperlink just has other text color. You can change color and text size with custom user CSS settings. Please add screen shot where link didn't work.

**Comment by rimugu** [comment]
Hi, the links do work, but they are not distinguishable from regular text. 
I tried in Preference/Reading Settings/Styles
a:link {font-weight: bold}
a:visited {font-weight: bolder}
But still look like any other text. Test it in the example epub files attached previously

**Comment by foobnix** [comment]
just try to add custom user CSS
a {font-weight: bold !important;}
or
a {color:#0000ff !important;}
