### ISSUE TITLE
proposition to honor .nomedia for excluding files

### ISSUE THREAD

**Issue by mmoole** [foobnix/LibreraReader#380]
I came across that Librera also displays all the files from Telegram / Whatsapp / etc download folders, and a lot of other folders that I have PDFs saved but don't need them displayed here.
Of course that makes sense in order to be able to read this, but how would I tell Librera to exclude files from a specific folder? Maybe it would just be simpler instead to honor `.nomedia` files that are meant for preventing media indexing for this?

**Comment by foobnix** [comment]
@mmoole  Thank you for a good idea, will be in beta today!
