### ISSUE TITLE
Incorrect value OPDS 

### ISSUE THREAD

**Issue by brechmos** [foobnix/LibreraReader#381]
I have a calibre server running on my machine with `--enable-auth`.  I have the purchased LibreraReader Pro on my android.  When I try to connect, the first time, it usually works, but everytime after it stops working. When I try to re-add the catalogue it says "Incorrect value OPDS".  

If I turn off `--enable-auth` everything works fine.  On, or off, Moon+Reader is able to get to the OPDS calibre server.  So, it feels like there is an authentication issue with LIbreraReader.

I hope this is the right place to post the issue even though I am not actually compiling from source the app.

I am using version 8.1.191.

**Comment by foobnix** [comment]
please send me the link and test account to fix by email librera.reader@gmail.com
