### ISSUE TITLE
feature request: supporting chinese language

### ISSUE THREAD

**Issue by sasasqt** [foobnix/LibreraReader#423]
test txt file:

========
1这是2个测试3。
this is 4 test
这是一个5.6%测试
这是一个 7测试
========

expected behavior:  working correctly,
in reality:
1这是个测试。
this is 4 test
这是一个.6%测试
这是一个 7测试
numbers(2,3,5) within chinese are missing in **TTS** and in **RSVP**: if there is no punctuation/blank in front of them.

also **RSVP** failed to recognize chinese characters words by words, it displays each line as one word.

hope this could be improved.
thx

**Comment by foobnix** [comment]
1) I don't understand Chinese but I see TTS show the correct result, just try other TTS voice.
2) As I know sometimes one hieroglyph with the second hieroglyph can mean different things, but in RSVP you will see only one hieroglyph. Is it make sense to make  RSVP for  Chinese?
![Screenshot-2019-10-16-10-27-38](https://user-images.githubusercontent.com/432440/66897697-31579380-f000-11e9-912f-f2a05ee15a60.png)
