### ISSUE TITLE
No more annotation feature?

### ISSUE THREAD

**Issue by cycneuramus** [foobnix/LibreraReader#434]
Am I missing something or did the annotation feature disappear from all versions after 8.1.191-fdroid?  

8.1.191-fdroid:

![8.1.191-fdroid](https://user-images.githubusercontent.com/56681631/67006912-7e159a00-f0e6-11e9-89ed-4910a1989afe.png)

8.1.305-fdroid:

![8.1.305-fdroid](https://user-images.githubusercontent.com/56681631/67006945-8cfc4c80-f0e6-11e9-82be-485c324c181f.png)

**Comment by foobnix** [comment]
yes, 8.1.191+ for F-Droid based on Mupdf 1.16.1 and this feature is not working good with Librera. I hope to fix this in the future.
