### ISSUE TITLE
Epub file is not loading properly!

### ISSUE THREAD

**Issue by DineshIT** [foobnix/LibreraReader#444]
I have downloaded an ePub content from the internet and view in the Microsoft edge. The alignments are fine, the file contains the video, image, widgets, and text.

While I tried to load the same file from the internal storage, the alignments are breaking into n number of pieces.

The book contains a total of 67 pages. But in the Librera reader, while I have open the epub file in book mode it is displayed as 515 pages. 
![Screenshot_20191024-131505 1](https://user-images.githubusercontent.com/12544773/67471800-a3b61c80-f66d-11e9-8d9e-caf4a65d408e.png)
![Screenshot_20191024-131353 1](https://user-images.githubusercontent.com/12544773/67471824-afa1de80-f66d-11e9-99b8-0f7ecdbf694f.png)

**Comment by foobnix** [comment]
could you please attach the book and also try the beta.librera.mobi Alpha build.
