### ISSUE TITLE
F-Droid flavor with OPDS

### ISSUE THREAD

**Issue by 532910** [foobnix/LibreraReader#477]
https://f-droid.org/en/packages/com.foobnix.pro.pdf.reader/

> For better security, the F-Droid version, is based on the latest MuPDF 1.16.1 and does not require access to the Internet.
For the above reason, some Internet-related features of Librera Reader are missing in its F-Droid version:
> 1) Access to OPDS (Calibre) Catalogs

Is it possible to add one more flavor, less secure, but with OPDS support?

**Comment by foobnix** [comment]
yes, please here
https://github.com/foobnix/LibreraReader/releases

**Comment by 532910** [comment]
Could it be added to f-droid?

**Comment by 532910** [comment]
Could you please add one more flavor for F-Droid with OPDS?

**Comment by 532910** [comment]
https://forum.f-droid.org/t/librera-with-opds/7710/6
Could you please add one more flavor for F-Droid with OPDS?

**Comment by foobnix** [comment]
Many F-Droid users want the most secure solution that is why no internet at all. You can use Librera PRO with OPDS and full internet functionality. I don't see the problem.

**Comment by 532910** [comment]
I don't ask you to modify the F-Droid flavor, but add one more flavor with Internet-related features that can be added to F-Droid.

> Many F-Droid users

How did you know this? I'm an F-Droid user and I want the full featured flavor.

> You can use Librera PRO with OPDS and full internet functionality. I don't see the problem.

Manually downloading it each update from  https://github.com/foobnix/LibreraReader/releases is not a solution.

**Comment by ikanakova** [comment]
@532910 I agree! I am F-Droid user as well and I want full featured flavor too.
