### ISSUE TITLE
Feature request: Markdown support

### ISSUE THREAD

**Issue by romanblanco** [foobnix/LibreraReader#493]
With Librera Reader I'm able to open markdown files, but only as a raw *.txt file, with no syntax applied.

What is missing to add to the application to enable the support?

**Comment by ivysrono** [comment]
+1

**Comment by foobnix** [comment]
Added in 8.2.21
![Screenshot-2019-11-28-12-07-08](https://user-images.githubusercontent.com/432440/69797006-aad5ca80-11d7-11ea-9404-06eea2def4a8.png)

**Comment by foobnix** [comment]
you can download from [beta.librera.mobi](http://beta.librera.mobi)
