### ISSUE TITLE
Librera folder inside user's home

### ISSUE THREAD

**Issue by 532910** [foobnix/LibreraReader#498]
LibreraReader creates `Librera` folder inside my home `/storage/emulated/0/`.

1. I do not need it, and don't expect the book reader will create some files in my home, moreover without my permission.
3. Some settings (theme at least) are stored there while it is very inappropriate place for user settings.
2. I'd prefer to store `Fonts` and `profile.Librera` that are inside `Librera` folder in the `Android/data/com.foobnix.pro.pdf.reader` as I'd like them to be removed with the app deletion.
3. Users that just tried and removed Librera app will live forever with the `Librera` folder.

**Comment by foobnix** [comment]
Old versions work in the way you write but Librera 8 supports synchronization. You can manually (with third-party apps) sync the /storage/emulated/0/Librera folder with any cloud app and have the same synced books, progress on all devices. All Library apps work with this folder so you have the same view in all apps.

**Comment by 532910** [comment]
Putting in into `Android/data/com.foobnix.pro.pdf.reader` will not break synchronization. As a `Storage` permission allows access to `Android`, it still be possible to use third-party apps for this, but Librera will not hard-depend on `Storage` permission more.

Moreover, right now some paths can be customized via configuration. Adding a customization for `Librera` path will allow to keep it in `/storage/emulated/0/` for those users who need it.

But the default behaviour should be to not create files in the HOME.

**Comment by foobnix** [comment]
Thank you for remark, I will make HOME path configurable.

**Comment by 532910** [comment]
Could you also point it to the `Android` folder by default?
