### ISSUE TITLE
getMupdfVersion error

### ISSUE THREAD

**Issue by SujeetKr9** [foobnix/LibreraReader#499]
java.lang.UnsatisfiedLinkError: No implementation found for int org.ebookdroid.droids.mupdf.codec.MuPdfDocument.getMupdfVersion() (tried Java_org_ebookdroid_droids_mupdf_codec_MuPdfDocument_getMupdfVersion and Java_org_ebookdroid_droids_mupdf_codec_MuPdfDocument_getMupdfVersion__)

**Comment by foobnix** [comment]
just rebuild mupdf 
cd Builder
./link_to_mupdf_1.16.1.sh
