### ISSUE TITLE
couldn't find "libmypdf.so"

### ISSUE THREAD

**Issue by SujeetKr9** [foobnix/LibreraReader#501]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.foobnix.pdf.reader.a1-olPa_SboVJJqPoVwYKPZHw==/base.apk"],nativeLibraryDirectories=[/data/app/com.foobnix.pdf.reader.a1-olPa_SboVJJqPoVwYKPZHw==/lib/x86, /data/app/com.foobnix.pdf.reader.a1-olPa_SboVJJqPoVwYKPZHw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libmypdf.so"

**Comment by foobnix** [comment]
just recompile mupdf

**Comment by Ramkesh9** [comment]
How i can compile mupdf for .so

**Comment by Sentoki** [comment]
@Ramkesh9 do you looked at readme? https://github.com/foobnix/LibreraReader#librera-build-on-mupdf-111-default

**Comment by ume-zara239** [comment]
how to  recompile mupdf

**Comment by ashwath20** [comment]
I did successfullt compiled mupdf  but getting this error [https://github.com/foobnix/LibreraReader/issues/707](url).

**Comment by bqytallhsirlkm** [comment]
> @Ramkesh9 do you looked at readme? https://github.com/foobnix/LibreraReader#librera-build-on-mupdf-111-default

can You Sir please explain it more
