### ISSUE TITLE
[feature] Sync progress like koreader

### ISSUE THREAD

**Issue by PhieF** [foobnix/LibreraReader#503]
Hi,
Just a feature description I would like to see one day
Koreader uses an interesting way to sync progress across devices, I guess it would be great

https://github.com/koreader/koreader/wiki/Progress-sync

And the selfhostable server

https://github.com/koreader/koreader-sync-server

Koreader host their own server, for users without any sysadmin knowledge
Sync is as anonymous as possible (well, md5) and doesn't use that much data, it would make librera compatible with e-ink ebooks readers, which would be great

Thanks for your great job

**Comment by foobnix** [comment]
The idea of Librera sync to be an independent from server.
You can sync the folder internal storage /Librera with any third party sync app. You can copy this folder to the new device and all progress, bookmarks will be here.
So you can try to configure koreader server to sync this folder and you will have sync progress
