### ISSUE TITLE
pages are not being fully displayed when it is zoomed

### ISSUE THREAD

**Issue by Saumen95** [foobnix/LibreraReader#514]
When I zoom a page,words are showed partially of those parts which get out of the main screen.To know what I mean, zoom a page and try to read the book sliding from side to side.You will see that words are not fully displayed. Thank you.

**Comment by foobnix** [comment]
This is expected behavior, if you want to make text large, just increase font size in the book settings.
Please read also
[http://librera.mobi/wiki/faq/](http://librera.mobi/wiki/faq/)
