### ISSUE TITLE
RSVP problem with 0CPL

### ISSUE THREAD

**Issue by youknow10** [foobnix/LibreraReader#525]
I want to use the RSVP feature with 0 CPL meaning just seeing 1 word per line. The problem is every time the program gets to the end of a line, it shows 2 words. 
To better showing the problem, consider this text:
"First sentence. Second sentence"
with 0CPL, it becomes:
"First"
"Sentence.Second"
"Sentence"
I tried it with 2 different books and got the same results. I'm using Version 8.2.11-fdroid.

**Comment by foobnix** [comment]
fixed in beta.librera.mobi
