### ISSUE TITLE
[Bug] Librera I/O read operations seem to fail on Android 10

### ISSUE THREAD

**Issue by opusforlife2** [foobnix/LibreraReader#538]
- The Folder tab is empty. Selecting a storage ("Internal Storage" or "Downloads") from the drop down doesn't work. Trying to add "New Storage" opens up the default file explorer, which shows a bar at the bottom saying "Allow Librera to access these folders and files" even though Storage permission is already granted. Granting this permission finally allows Librera to show files and folders in the Folder tab.
- Trying to manually scan using the "Find" button doesn't work. Trying to add a folder to scan doesn't work.
- Opening the app for the first time after installing lets it scan for books. But tapping the Rescan button in the Library tab empties it instead.

Librera 8.2.11-fdroid.

**Comment by foobnix** [comment]
on F-droid is not final build, just try here https://github.com/foobnix/LibreraReader/releases
or beta.librera.mobi

**Comment by opusforlife2** [comment]
Alright. I opened an issue on their Gitlab to update Librera.

**Comment by licaon-kter** [comment]
Having the same issue on 8.2.29 too, F-Droid
