### ISSUE TITLE
Feature request: treat .okular files as .zip files

### ISSUE THREAD

**Issue by i5qme2b944w3** [foobnix/LibreraReader#543]
Okular is document viewer for Linux with a feature for annotating .djvu files. After annotating a `[filename].djvu`, it stores the result as `[filename].okular`. But really, `[filename].okular` is just a zip file containing the original `[filename].djvu` and some xml's.

Since Librera can already open zip files, would it be possible to treat any file with a .okular extension as though it were .zip instead? That would allow Librera to view Okular's annotated djvu's (without the annotations, of course), without the user having to unzip them in a separate app first.

**Comment by foobnix** [comment]
Please attach some .okular file samples

**Comment by i5qme2b944w3** [comment]
Here you go:
[okular_sample.tar.gz](https://github.com/foobnix/LibreraReader/files/4161837/okular_sample.tar.gz)

**Comment by foobnix** [comment]
Added in 8.2.35 (beta.librera.mobi)
