### ISSUE TITLE
PDF content not shown

### ISSUE THREAD

**Issue by maggu2810** [foobnix/LibreraReader#559]
Hi,
I downloaded a PDF file and opened it in the Librera Reader currently available from F-Drood (8.2.29-fdroid).

It looks like an empty PDF, so I tried other readers and they have been able to render the content.

The PDF I used is available here: https://www.pfaenderbahn.at/Portals/0/download/wandern/wanderkarte2016_1.pdf
It is a hiking map.

Thank you for your great app!
If I can provide further information, let me know.

**Comment by foobnix** [comment]
Can't reproduce, just try final beta.librera.mobi build

**Comment by maggu2810** [comment]
I installed "Librera Beta-8.3.7--arm64.apk" (2020-03-08 23:49).
If I open the PDF I can choose (as for every PDF) between three different reading modes.
I don't know the english names as they are shown german on my system:
* Modus "Vertikales Blättern"
* Modus "Horizontales Blättern" (Buch)
* Modues "Musiker"

If I choose "vertikales Blättern" the map is shown but I cannot center it. The top side of the map is on the middle of the screen. I can zoom the map, and so get it full on screen but always it seems that the half is out of screen.

If I choose "horizontales Blättern" the map seems to be correctly centered now. All fine in this mode.

I did not use the "Musiker" mode before so I don't know how it is working.

Can you please compare the first and the second mode and tell me if this is really the desired behaviour.
