### ISSUE TITLE
Feature:Highlight lines and words  

### ISSUE THREAD

**Issue by Saumen95** [foobnix/LibreraReader#562]
It will be quite helpful for the readers if librera support text and line highlighting. It will keep track of important lines or words that we want to remember especially.

**Comment by Saumen95** [comment]
![Screenshot_2020-03-03-00-41-10-760_com flyersoft moonreaderp](https://user-images.githubusercontent.com/43635450/75706702-8e08d180-5cb5-11ea-8748-aef3b0955af2.png)
Exampletaken from another reader

**Comment by moshpirit** [comment]
I think this is a duplicated issue of #382
