### ISSUE TITLE
PDF reflow does not work

### ISSUE THREAD

**Issue by nicoursi** [foobnix/LibreraReader#565]
After tapping on "scroll mode", and then "reflow PDF", nothing happens.
I tried with different pdfs. They all reflow with "Book Reader" from F-droid but nothing happens on librera.

**Comment by foobnix** [comment]
very strange, please attache pdf file

**Comment by darkenedcolossal** [comment]
I can confirm "nothing happens". There is not even a folder Downloads under Internal/Librera. Creating it manually did not change anything.
Is there any logging? Anything to help debug?

**Comment by foobnix** [comment]
can't reproduce, pdf text reflow for dummy.pdf works perfect on my devices

**Comment by darkenedcolossal** [comment]
**Solution:**
I still had the problem after clearing cache/storage for the app and uninstalling/reinstalling it. But when I renamed (deleted) the folder Internal/Librera PDF reflow started working for me, too! :)

**Comment by HotshotGT** [comment]
Having the same issue with both the current F-Droid version (9.1.29) and the previous one (9.1.14). Reflow stopped working at some point, and no combination of folder deletion, cache/storage clearing, and reinstalling has fixed it.

**Comment by foobnix** [comment]
fixed in 9.1.35

**Comment by Opening-Button-8988** [comment]
> fixed in 9.1.35

@foobnix 

Tested this on fdroid build, clicking on Reflow PDF brings up a "Please wait ..." loading screen and never finishes loading. I also can't click on X to close it, can't swipe right to go back. I need to close app to restore function.

Tried it on PDF books and also: https://sample-files.com/downloads/documents/pdf/basic-text.pdf

Tested again with a fresh install on a different android profile and it works. It must be something to do with the settings. 

Restored default settings and it works!
