### ISSUE TITLE
is it supportable for andorid studio ? error coming with json file missing 

### ISSUE THREAD

**Issue by Ramkesh9** [foobnix/LibreraReader#567]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processAlphaDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 

please help me.

**Comment by fermat2a** [comment]
Hi,

I failed with the same. I searched around and it seems that this file is needed attaching the app to the google services. You need to set the API key with this file. I already created a credentials.json file following https://developers.google.com/identity/sign-in/android/start-integrating. But I have no idea how this google-services.json has to look like or where to obtain it. Can someone give me a hint how to create google-services.json?

For the moment I use the FDroid builds because they do not use google-services. This way I could create an apk and install it in an AVD. But until now I did not manage to automatically start it or to debug the app.

bests

fermat2a

**Comment by Ramkesh9** [comment]
@fermat2a How do you get complie ?

System.loadLibrary("mypdf")
 System.loadLibrary("mobi");
 System.loadLibrary("antiword");

Actually i am unable to compile this .

**Comment by fermat2a** [comment]
I even do not understand your question... The README now describes what I did to get a keystore and make it available for gradle and which NDK version you need in Android Studio. Thereafter I was able to build the Fdroid build. This works also from Android Studio by calling the right task.

**Comment by Ramkesh9** [comment]
Actually i am unable to compile JNI files, like MUPDF .

**Comment by fermat2a** [comment]
So, you get an error calling link_to_mupdf_1.11.sh? What error do you get there?

**Comment by Ramkesh9** [comment]
couldn't find "libmypdf.so"

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.foobnix.pdf.reader.a1-olPa_SboVJJqPoVwYKPZHw==/base.apk"],nativeLibraryDirectories=[/data/app/com.foobnix.pdf.reader.a1-olPa_SboVJJqPoVwYKPZHw==/lib/x86, /data/app/com.foobnix.pdf.reader.a1-olPa_SboVJJqPoVwYKPZHw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libmypdf.so"

This error i am facing.

**Comment by fermat2a** [comment]
This should be created by link_to_mupdf_1.11.sh. Have you called it? Can you copy the complete output to a file and attach it here?

**Comment by fermat2a** [comment]
I mean the output when calling link_to_mupdf_1.11.sh.

**Comment by Ramkesh9** [comment]
Actully i am not much experienced working with .sh files, and i dont know how to compile thease files in andoid studio, never worked with ndk compatiable library's earlier, 
i am sure i may be missing any step, but dont know which one,

The Process i followed with this project to compile:
-  i just clone the repo/ Project
- import it in android studio (Androd studio version : 3.6.1)
- Selected FDroid build variant and tried to compile 
And Found above error "couldn't find "libmypdf.so", which i mentioned above.

**Comment by fermat2a** [comment]
O.K., let`s start slowly... Which operating system are you running on your build machine?

**Comment by Ramkesh9** [comment]
Yeah sure, 
I am using mac os x.

**Comment by fermat2a** [comment]
How did you install the required build libs there?

**Comment by Ramkesh9** [comment]
I just import the project in android studio after cloning it.

**Comment by Ramkesh9** [comment]
Many developers similar to me are facing same problem for compiling this project.

**Comment by fermat2a** [comment]
Then all these developers need to learn to read... You need to install
the required libs before. This can be done using Ubuntu (linux)
directly using apt-get. I am not sure, how to do this under MacOS.
Perhaps the packages are available in homebrew.

To make it easy I recommend using a VM and install Ubuntu. There you
can install the required libs, Android Studio (do not forget to install
the right NDK, google will help you to find out how) and run the script
to build mupdf...

When you did so, you are welcome to ask me again if you still have
problems.

**Comment by Ramkesh9** [comment]
Ok thank you for tour time and suggestion.
I will follow it.

**Comment by foobnix** [comment]
thanks for instruction in the README.md
