### ISSUE TITLE
Clouds support for Dropbox should use App folder not full access

### ISSUE THREAD

**Issue by shbach** [foobnix/LibreraReader#569]
![image](https://user-images.githubusercontent.com/5298745/77685919-6b3aa780-6f59-11ea-824a-43806c42bc91.png)

Currently in order to use the cloud support for Dropbox, the access type is for the full dropbox. Unless this is necessary for Librera to function, the access should be restricted to app folder for security/privacy.

![image](https://user-images.githubusercontent.com/5298745/77686002-8a393980-6f59-11ea-81cd-9174978390a4.png)

See Dropbox documentation: https://www.dropbox.com/developers/reference/developer-guide

**Comment by foobnix** [comment]
Librera use CloudRail lib for working with clouds and can't do anything with this.
Clouds support may be removed soon from Librera because  CloudRail library is not supporting for 3 years.
