### ISSUE TITLE
Feature request: Add more online book website

### ISSUE THREAD

**Issue by Saumen95** [foobnix/LibreraReader#582]
I use pdfdrive.com and Archieve.org to download my books.They are renowned website for getting pdf and ebooks.Can you please add those servers to librera please?

keep up your good work man!

**Comment by foobnix** [comment]
Is it content legal on your site?
Please send me opds (calibre) link for your site

**Comment by Saumen95** [comment]
https://www.pdfdrive.com/

**Comment by Saumen95** [comment]
@foobnix https://archive.org/
You mean these?

**Comment by foobnix** [comment]
https://en.m.wikipedia.org/wiki/Open_Publication_Distribution_System

**Comment by Saumen95** [comment]
Thank you for responding.As it seems its may be not possible to get calibre or OPDS link for those site. I thank you agai for your good work sir,and closing the thread
