### ISSUE TITLE
Ошибка при выполнении команд make, ndl-build.

### ISSUE THREAD

**Issue by Vladzrabbit** [foobnix/LibreraReader#586]
Здравствуйте, нужна помощь.
При попытке выполнить all-release.sh и выполнении link_to_mupdf_1.16.1.sh возникают ошибки:
MUPDF : 1.16.1
==================
==================
./link_to_mupdf_1.16.1.sh: line 30: make: command not found
./link_to_mupdf_1.16.1.sh: line 31: make: command not found
==================
./link_to_mupdf_1.16.1.sh: line 59: ndk-build: command not found
==================
MUPDF: /c/Users/vlad/LibreraReader/Builder/mupdf-1.16.1/platform/java
LIBS: /c/Users/vlad/LibreraReader/Builder/../app/src/main/jniLibs
================== 

При этом NDK 21 версии в PATH я его прописал:
![ndk](https://user-images.githubusercontent.com/51747004/80577401-817fcb80-8a0f-11ea-9051-1dd95cfef8b4.PNG)

**Comment by foobnix** [comment]
этот скрипт написан для Linux, на Windows не проверял. 
Переходите на Linux

**Comment by Vladzrabbit** [comment]
Спасибо
