### ISSUE TITLE
Librera cannot open cbz files via Nextcloud

### ISSUE THREAD

**Issue by emfrost** [foobnix/LibreraReader#588]
I'm using Nextcloud to share cbz files across devices with limited storage. Tapping the file in Nextcloud downloads it, but it fails to open, saying "No app set up to handle this file type". Opening it via the regular file manager works fine.

Nextcloud uses mimetypes to open files, and serves cbz files correctly as application/comicbook+zip. PDF and azw3 formats open correctly, so I believe this issue would be a simple fix, but I don't know enough about Android to fix it myself.

There are definitely workarounds, but it would be nice to be able to download and open books from the same application. I'm sure this issue extends to other apps as well.

**Comment by foobnix** [comment]
Thanks, fixed in new beta.librera.mobi (added cbz, cbr mime types)

**Comment by emfrost** [comment]
Thank you!
