### ISSUE TITLE
Library always adds files in Download

### ISSUE THREAD

**Issue by darkdragon-001** [foobnix/LibreraReader#592]
Even if I select only my private `eBooks` folder, items in `Downloads` folder are always shown in the _Library_ tab.

**Comment by foobnix** [comment]
You can specify paths for the librery
http://librera.mobi/wiki/faq/update-the-library/

**Comment by darkdragon-001** [comment]
This is what I did, but the items in `Downloads` never disappeared, even if I removed everything except for `eBooks`...
