### ISSUE TITLE
[Issue] Include footnotes directly in the text not working for EPUB files

### ISSUE THREAD

**Issue by creonrex** [foobnix/LibreraReader#595]
Html footnotes linked to text by `<a>` tag with valid `href` attribute in .epub files are not showing in the text when the option _include footnotes directly in the text_ is selected.

Tested on Moto G4 and Xiaomi Mi A2.

**Comment by foobnix** [comment]
please attach (or send my email) the book to check but for epub books it's not possible to include footer notes due to complicated book formatted text
