### ISSUE TITLE
Юзабилити

### ISSUE THREAD

**Issue by mtxadmin** [foobnix/LibreraReader#596]
Иван, извините, что по-русски. Но с юзабилити у программы просто тихий ужас. Я минут за десять так и не нашел, как избавиться от прикрепленных тулбаров. Как нормально скроллить текст, не выезжая вбок за границы текста. Как нормально вызывать настройки из Scroll Mode, в конце концов - ну почему дабл-тап не вызывает их, например?

Досадно, хороший с виду проект и книги с ходу открыл, с которыми Moon Reader не справился.

**Comment by foobnix** [comment]
> как избавиться от прикрепленных тулбаров
Один клик в центре страницы

>как нормально скроллить текст, не выезжая вбок за границы текста.
Замочек закройте (справа внизу иконка)

>Как нормально вызывать настройки из Scroll Mode
Сверху иконка настройки 

[wiki.librera.mobi](http://wiki.librera.mobi)
