### ISSUE TITLE
Clicking on Epub contents doesn’t work 

### ISSUE THREAD

**Issue by Saumen95** [foobnix/LibreraReader#602]
In the new Version when I click on contents of a epub ,It doesn’t respond at all.

**Comment by foobnix** [comment]
Maybe it depends on the book? (I can't reproduce, contents are working for me, please send me the book where are contents not working now)

**Comment by Saumen95** [comment]
> Maybe it depends on the book? (I can't reproduce, contents are working for me, please send me the book where are contents not working now)

No.I Have tested it using librera 8.3.45(older version) and Fbreader also.Contents worked there.But in 8.3.69 its not working. may be you are using f droid version? I havent checked fdroid release yet

**Comment by foobnix** [comment]
Please add some screenshots

**Comment by Saumen95** [comment]
> Please add some screenshots
> […](#)

@foobnix 
![Screenshot_2020-06-04-18-49-14-257_com foobnix pro pdf reader](https://user-images.githubusercontent.com/43635450/83758700-fcb54c80-a661-11ea-9113-ca7c7e0c074b.png)
Here, The contents are highlighted as you can see.When I touch then,it should go to the respective chapter.But librera 8.3.69 doesnt respond at all when I touched the contents

**Comment by foobnix** [comment]
hm, very strange I can't reproduce with my books, please also try beta.librera.mobi

**Comment by omgold** [comment]
Same problem for me. Also implies opening words in dictionary on long click not working anymore.

**Comment by foobnix** [comment]
fix will be soon or you can try beta.librera.mobi
