### ISSUE TITLE
Text won't be unselected after touch the "X" button of pop-out box of selected text.

### ISSUE THREAD

**Issue by stevenleeS0ht** [foobnix/LibreraReader#607]
When touch a certain area of text for a while, this area of text will be selected, and a selection box will pop-up, When I touch the background area to cancel the selection, everything goes fine, but when I touch the "cross" button on the right upper corner of pop-up box, the box will disappear. But the selection won't be canceled.

However, when I want to make pop-up box appear again. I need re-long-touch this area of text, which there is no difference as the text is not selected.

Is it possible to make "cross"("close") button behavior as same as the touch background behavior?

**Comment by foobnix** [comment]
This feature for more accurate text selection, you can close the dialog and continue text selection.
You can also use back button to hide the dialog and text selection.
