### ISSUE TITLE
Problem in cover parsing

### ISSUE THREAD

**Issue by Saumen95** [foobnix/LibreraReader#609]
Librera has three colour profile dark,light,amoled dark. Not all the cevers are parsed correctly when we switch between them. 
![Screenshot_2020-06-13-19-25-47-792_epub reader](https://user-images.githubusercontent.com/43635450/84570052-37ae3300-ad7a-11ea-95fd-2c59cea403df.png)
![Screenshot_2020-06-13-19-26-26-709_epub reader](https://user-images.githubusercontent.com/43635450/84570058-3c72e700-ad7a-11ea-8ebe-91a4ecd0d779.png)
![Screenshot_2020-06-13-19-27-36-364_epub reader](https://user-images.githubusercontent.com/43635450/84570062-43015e80-ad7a-11ea-84eb-0eea733e82bf.png)

Here I added some ss of dark and light mode. As you can see, a book named Atomic Accidents  cant get it cover parsed in the light and Dark mode.

I know its a little fix may be.Still I think the bug report helps.

**Comment by foobnix** [comment]
Please check the final beta.librera.mobi it looks the problem has fixed
