### ISSUE TITLE
[Issue] [Regression] Switching between day and night mode changes the page number

### ISSUE THREAD

**Issue by adarazs** [foobnix/LibreraReader#614]
I'm reading an epub book and whenever I switch between the day/night mode, the current page and the total page number changes and I find myself on a different page. Switching back to the previous mode brings me back to the previous page and total page count.

This only happens in my current book, not in another one I tried. The bug is present in both `8.3.69-fdroid` and `8.3.75-droid`, but stays on the same page and works fine in `8.3.45-fdroid`.

See the example image: https://i.imgur.com/XkjY7B3.png (I do nothing else than touch the sun icon between the two screens.)

If you need the book to test or more information, let me know.

**Comment by foobnix** [comment]
fixed in 8.3.79

**Comment by adarazs** [comment]
Thank you. I will test it when it hits F-Droid.

**Comment by adarazs** [comment]
I verified that it is fixed in 8.3.83-fdroid. Thank you once again.
