### ISSUE TITLE
Non FOSS libs in the F-Droid version?

### ISSUE THREAD

**Issue by licaon-kter** [foobnix/LibreraReader#616]
https://forum.f-droid.org/t/librera-reader-containing-admob/10341

**Comment by foobnix** [comment]
FDroid may contain only stub classes for the ads integration. Only the Free version with AdMob.
Even more, F-Droid app version doesn't have access to the internet permission.

**Comment by licaon-kter** [comment]
Right stubs https://github.com/foobnix/LibreraReader/tree/master/app/src/fdroid/java/com

Indeed, there raise false positives unfortunately.

**Comment by ildar** [comment]
> Indeed, there raise false positives unfortunately.

Also you cannot fix this with adding an exception to a scanner because scanners are many.
So in fact many scanners report false positive.showing stubs wasn't a good decision for this.

**Comment by licaon-kter** [comment]
Maybe the point was to have a FOSS app and not to "appear" clean in random purity scanners @ildar
