### ISSUE TITLE
Annotate pdf

### ISSUE THREAD

**Issue by anishmittal2020** [foobnix/LibreraReader#617]
Version: 8.3.83-fdroid

When I select the text by long pressing it, I don't get any option to annotate it? Could you please tell how could we annotate text?

Kind Regards.

**Comment by foobnix** [comment]
Annotate works only for PDF on internal storage and only in Scroll mode

**Comment by anishmittal2020** [comment]
Thanks @foobnix! Is this issue resolved: [No more annotation feature? · Issue #434 · foobnix/LibreraReader](https://github.com/foobnix/LibreraReader/issues/434)?

Because annotations don't appear in Version: 8.3.83-fdroid but I get it on versions older than 8.1.191-fdroid.

**Comment by Yolakalemowa** [comment]
How's do I annotate exactly? I'm on scroll mode and i see no option.
