### ISSUE TITLE
Rendering markdown (using gitbook or wiki linkformat)

### ISSUE THREAD

**Issue by gbraad** [foobnix/LibreraReader#625]
It would be nice if Markdown files can be rendered, and perhaps even traversed as gitbook (using the index.md/gitbook.md IIRC) or as github-wiki by placing all files into a generated table of contents and traverse links between files. any external link would use a browser intent.

**Comment by foobnix** [comment]
Added in new beta.librera.mobi support of gitbook
Just open SUMMARY.md or click "Bind a book"
![Screenshot-2020-07-30-11-40-39](https://user-images.githubusercontent.com/432440/88901586-a592b900-d259-11ea-9d8c-1e84742130ba.png)
![Screenshot-2020-07-30-11-40-30](https://user-images.githubusercontent.com/432440/88901592-a6c3e600-d259-11ea-8491-4811f135d8f6.png)

Please send me more gitbook samples if something not works
