### ISSUE TITLE
[Feature Request] Automatic theme (light/dark), follow system

### ISSUE THREAD

**Issue by crisalis2** [foobnix/LibreraReader#630]
In Android 10 it's possible to make an app automatically apply a light or dark theme depending on the system wide setting. It'd be nice if Librera had an option to let you set a preferred UI theme for light and dark modes, and then automatically applied either of them depending on the system setting. Ideally, this would also apply to the reader theme, which already has separate light and dark versions.
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by xmha97** [comment]
any updates?

**Comment by foobnix** [comment]
Fixed in beta, choose theme "system"

**Comment by ojppe** [comment]
Great! It would be perfect if it applied to the reader as well

**Comment by xmha97** [comment]
Thanks. 🙏

**Comment by xmha97** [comment]
> Fixed in beta, choose theme "system"

Thanks. 🙏
Please select "System" by default.

**Comment by crisalis2** [comment]
I think two things are still necessary:
1. Make it apply to the reader theme as well.
2. Make the light and dark theme configurable when it's set to follow system. For example I want the dark OLED theme as the dark theme, and I want the theme to follow the system setting, but if I set that, the dark theme is sadly set to the default dark theme instead of the desired dark OLED theme.
Thanks.
