### ISSUE TITLE
[Request] Consider a F-Droid Alternative Version With Calibre Support 

### ISSUE THREAD

**Issue by grravity** [foobnix/LibreraReader#651]
Currently the F-Droid version has Calibre removed, it would be nice to have a second version that keeps Calibre.
It's FOSS, and self-hosted so I can't see it being privacy concerns, unlike Google Drive or such.

It would be nice to be able to connect to Calibre, without needing to use the Google play version (which isn't possible for users sith Degoogled devices)  

There's currently no maintained Calibre readers on F-Droid, so this would be appreciated.

**Comment by foobnix** [comment]
you can download PRO here https://github.com/foobnix/LibreraReader

**Comment by grravity** [comment]
Is there any reason as to why the Pro has not simply been pushed to F-Droid alongside the other?

**Comment by hlvs44** [comment]
Hi, I'm agree, it would be very usefull to import calibre bookmarks stored in the epub file (in META-INF/calibre_bookmarks.txt) or to export in the same format.
Specially when using for studing and not just narrative or pleasure books, bookmarks are very important.
See attachment for calibre format. 
Is it available on F-Droid?
Thanks a lot!

[calibre_bookmarks.txt](https://github.com/foobnix/LibreraReader/files/6328861/calibre_bookmarks.txt)
