### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [foobnix/LibreraReader#652]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is 8.3.100, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
<img width="473" alt="bug-foobnix-2" src="https://user-images.githubusercontent.com/18572115/103194096-6c9a6580-4919-11eb-9a89-272ce19dbcea.png">

**Comment by foobnix** [comment]
thanks, fixed in beta
