### ISSUE TITLE
[Privacy] WebView

### ISSUE THREAD

**Issue by duggalsu** [foobnix/LibreraReader#654]
Opt out of sending metrics to Google when using WebView. Add the following to the manifest -
```
<meta-data android:name="android.webkit.WebView.MetricsOptOut" android:value="true" />
```
https://developer.android.com/guide/webapps/webview-privacy

**Comment by foobnix** [comment]
Thanks, fixed in beta

**Comment by woheller69** [comment]
According to the docs it must be in the <application> section of the manifest.

Currently it is outside...
