### ISSUE TITLE
html list attributes not recognised

### ISSUE THREAD

**Issue by ourairquality** [foobnix/LibreraReader#655]
The attributes for the html ordered list elements are not recognised. This affects html and epub files. Here is a simple example:

```
<ol start="5">
  <li> expect 5</li>
  <li> expect 6</li>
  <li value="10"> expect 10</li>
  <li> expect 11</li>
</ol>

<ol reversed="1" start="5" type="a">
  <li> expect e</li>
  <li> expect d</li>
  <li value="10"> expect j</li>
  <li> expect i</li>
  <li> expect h</li>
</ol>
```

Might this be due to the Jsoup.clean method and the Whitelist used for this, and if so then might adding these attributes to the safe list addressed this issue. There is a usage in HtmlExtractor.java and might that be the only relevant one, or is the use in zipmanager/SendReceiveActivity.java also relevant. Here is a suggestion for HtmlExtractor.java:

```
Safelist safelist = Safelist.basic()
   .addAttributes("ol", "reversed", "start", "type")
   .addAttributes("li", "value");
string = Jsoup.clean(html.toString(), safelist);
```

Perhaps there will be other attributes that are safe and appropriate to add as well.

Edit: ```<ul>``` does not accept the ```type``` attribute in epub3, removed.

**Comment by foobnix** [comment]
It looks like https://www.mupdf.com/ does not support these attributes, Librera use mupdf for rendering.
