### ISSUE TITLE
Most of English offline learner's dictionaries don't work

### ISSUE THREAD

**Issue by chessman** [foobnix/LibreraReader#657]
I tried a few installed offline learner's dictionaries but only one partially works:

- [Cambridge Advanced Learner's Dictionary](https://play.google.com/store/apps/details?id=org.cambridge.dictionary.advanced.learners.fourth). Adds an icon to "Text" popup but returns "Dictionary is unavailable" for all translation attempts.
- [Oxford Advanced Learner's Dictionary](https://play.google.com/store/apps/details?id=com.oup.elt.oald10_gp). Same as above.
- [Merriam-Webster Learner's Dictionary](https://play.google.com/store/apps/details?id=com.merriamwebster.learners). It actually works but often it just opens the app without filling in a word.
- [Longman Dictionary](https://play.google.com/store/apps/details?id=dictionary.english.freeapptck). It doesn't even have an icon in "Text" popup.

**Comment by foobnix** [comment]
It may be a problem in those apps, they not correctly get the words from other apps.
You can try to share text from the web browser or other apps to those dictionaries to check the problem exists or not.

It the problem only with LIbrera I will check.

**Comment by chessman** [comment]
Turned out that the problem was on my side. The dictionaries work after purchase.
