### ISSUE TITLE
Donates

### ISSUE THREAD

**Issue by bergentroll** [foobnix/LibreraReader#658]
It is an old users' wish, as I see on 4PDA. Therefore let me say it again: it's inconvenient for Free Software lovers and Google non-lovers to buy Pro version on play.google. There is pretty useful possibility [to make repository sponsored](https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) with plenty of funding methods.

**Comment by maximilianduell** [comment]
I would even consider buying a yearly subscription for some reasonable price to support the continued development of Librera.

**Comment by Iey4iej3** [comment]
There is a possibility on [Patreon](https://www.patreon.com/librera) which is described in the readme. Is it OK?

**Comment by bergentroll** [comment]
@Iey4iej3 @foobnix 

Well, yes. Thank you. Also because of some current troubles with transactions it also may be nice to have some crypto account.
