### ISSUE TITLE
[Feature] Request for multiple pdf to be opened at the same time

### ISSUE THREAD

**Issue by Thewisem** [foobnix/LibreraReader#663]
I would like to have the option to open multiple pdf files. I am kind of a multitasker. It would really be helpful if you could add this feature

**Comment by foobnix** [comment]
You can run two instances of the application, for example, Librera pro and LIbrera F-Driod and switch between them

**Comment by groszdaniel** [comment]
> You can run two instances of the application, for example, Librera pro and LIbrera F-Driod and switch between them

That works as a workaround (as does cloning the app), but it has downsides, like that settings and recent books are not shared between the apps, and you can only switch between a fixed number of books this way. It's possible for an Android app to support opening multiple activities of it at a time such that one can switch between them like between apps (for instance the old Android Browser opened tabs line that); it would be a nice feature to support this natively. My use case is to switch between a textbook, and scanned lecture notes "bound as a book".
