### ISSUE TITLE
Can't use QuickDic dictionary

### ISSUE THREAD

**Issue by siccovansas** [foobnix/LibreraReader#698]
My local dictionary app [QuickDic](https://github.com/rdoeffinger/Dictionary) (also available on F-Droid) isn't in the list of dictionaries to use in Librera. I looked at Librera's FAQ and searched the issues, and I get the impression that QuickDic needs the be added to Librera's code as a valid dictionary app?

**Comment by pidario** [comment]
It applies also to ColorDict and English Dictionary Offline. Downgrading to 8.3.100-fdroid (4000) solves the problem.
I didn't try the play store version but I guess the issue will also be there.

**Comment by foobnix** [comment]
please test in 8.3.135 version

**Comment by pidario** [comment]
Fixed 😊

**Comment by siccovansas** [comment]
@foobnix it is indeed fixed in  8.3.135, awesome, thanks!
