### ISSUE TITLE
Replace three dots with ellipsis

### ISSUE THREAD

**Issue by Valdnet** [foobnix/LibreraReader#711]
There are three dots in the following text strings. The ellipsis `…` should be used in order to be correct. 

https://github.com/foobnix/LibreraReader/blob/69eb7332714b08656ff98a219fd97ed7901b5aa3/app/src/main/res/values/strings.xml#L231
https://github.com/foobnix/LibreraReader/blob/69eb7332714b08656ff98a219fd97ed7901b5aa3/app/src/main/res/values/strings.xml#L288
https://github.com/foobnix/LibreraReader/blob/69eb7332714b08656ff98a219fd97ed7901b5aa3/app/src/main/res/values/strings.xml#L339
https://github.com/foobnix/LibreraReader/blob/69eb7332714b08656ff98a219fd97ed7901b5aa3/app/src/main/res/values/strings.xml#L345
https://github.com/foobnix/LibreraReader/blob/69eb7332714b08656ff98a219fd97ed7901b5aa3/app/src/main/res/values/strings.xml#L359
https://github.com/foobnix/LibreraReader/blob/69eb7332714b08656ff98a219fd97ed7901b5aa3/app/src/main/res/values/strings.xml#L535

**Comment by ComedyTomedy** [comment]
Maybe you could open a PR, since it's an easy fix?

**Comment by Valdnet** [comment]
Done 😉.
