### ISSUE TITLE
OPDS browser doesn't correctly handle azw3 mime type

### ISSUE THREAD

**Issue by RandomDennisLee** [foobnix/LibreraReader#715]
Librera reader OPDS browser supports "application/x-mobi8-ebook" and "application/azw3", but not yet "application/vnd.amazon.mobi8-ebook", which should be the technically correct one. 

"application/x-mobi8-ebook" was deprecated in 2016 and changed to "application/vnd.amazon.mobi8-ebook". Support for "application/x-mobi8-ebook" should remain for the sake of backward compatibility, but "application/vnd.amazon.mobi8-ebook" should be added as a recognised mime type.

Currently, attempting to open a file of mime type "application/vnd.amazon.mobi8-ebook" in the OPDS browser results in an unsupported format error message, despite the book being a perfectly valid azw3 file.

**Comment by foobnix** [comment]
added support for mime type "application/vnd.amazon.mobi8-ebook"
