### ISSUE TITLE
Marking/copying of & searching for text on first page (page 1) doesn't work

### ISSUE THREAD

**Issue by TueTchen** [foobnix/LibreraReader#725]
Dear Libera Developer,

thank you for your efforts for this fantastic app!

As already sent by eMail on 13th of Juli 2021, now tested with latest versions (8.3.135 + 8.3.142) again --> still open:

There is a little issue that crept in over one of the last versions a few months ago (I think it came within a version at the end of 2020):

Page 1 is now handled "specially', so:
- marking/copying text doesn't work on p.1
- searching text doesn't find results in p.1

Perhaps there's a 'senseful functionality behind' and somewhere in the depht any setting checkbox to 'use old behaviour' is found or else, but I couldn't find anything.

Please could you check this issue and - if bug - fix it in one of the next versions?

Kind regards from Germany!
Peter

**Comment by TueTchen** [comment]
Add.: Screenshots of my settings (German):

![Screenshot_20211018-090823](https://user-images.githubusercontent.com/63955513/137684743-ba3ed4be-ed19-49bb-8336-7848a2e46946.jpg)

![Screenshot_20211018-090924](https://user-images.githubusercontent.com/63955513/137684770-28532a4d-7839-4832-aa19-a61190211377.jpg)

![Screenshot_20211018-090952](https://user-images.githubusercontent.com/63955513/137684800-e6b0b572-750f-43e7-9896-53a15517a18c.jpg)

**Comment by foobnix** [comment]
Librera use Mupdf and it's sometimes crash with the first-page text
So I disable the extract page text from the first page.
I will enable this feature for F-Droid build (not so many users)

**Comment by TueTchen** [comment]
Thank you VERY much!!
