### ISSUE TITLE
[Bug] OPDS .CBR files show up in Librera as .cbt, and are saved as the wrong format, leading to Librera being unable to handle them

### ISSUE THREAD

**Issue by RandomDennisLee** [foobnix/LibreraReader#726]
Steps to reproduce:
Access .CBR file via OPDS
Shows up in OPDS browser as .CBT
Download file, saved with .CBT extension
.CBT file disappears from library after refresh (which is a bug on its own)
Librera is unable to see in library

**Comment by foobnix** [comment]
fixed
