### ISSUE TITLE
OPDS search replacing spaces with +

### ISSUE THREAD

**Issue by rg9400** [foobnix/LibreraReader#728]
I noticed Librera does not properly handle searching OPDS catalogs when using multiple words. No results are returned, but if I use underscores instead of spaces, it works, e.g. `The Way of Kings` returns no results, but `The_Way_of_Kings` would. I set up a feed and captured the URLs being used. Librera is replacing spaces with `+` signs, e.g. `opds/search/the+way+of+kings`. But a bunch of other apps I tested do not do this. Instead, they keep the space, searching `opds/search/the way of kings`. This lets the OPDS catalog handle the space encoding properly. With + instead, it breaks.

While there is a workaround, it is inconvenient. Would be nice to get this fixed

**Comment by foobnix** [comment]
fixed in beta.librera.mobi

**Comment by rg9400** [comment]
> fixed in beta.librera.mobi

@foobnix is this  fixed in 8.4.1 or requires the specific beta apk? I am using the beta version from Google Play Store (version 8.4.1 111-librera), but it's still not working. Checking OPDS access log, it's still using `+`.

Also, side note, but is Librera Reader Beta available for the pro version? I have to use the normal version to get the beta version through Google Play Store.

**Comment by foobnix** [comment]
I have added replacements space " " to "+" - I see the most OPDS works in that way.
If I search with "_" my OPDS return not correct results
