### ISSUE TITLE
[FR] 2 or 3/4/5 books opened at the same time

### ISSUE THREAD

**Issue by ildar** [foobnix/LibreraReader#740]
In some cases users need to have two / three books side by side on their big and shiny Android tablets.
I've seen an elegant solution for this in Material Files: choosing "New Window" makes a new instance in the Recent Apps (https://github.com/zhanghai/MaterialFiles/issues/181#issuecomment-559885690)
Would this be implemented ?
thanks!

**Comment by foobnix** [comment]
You can install two apps Librera and Librera PRO and switch between them.
Recent books and progress will be the same in both apps

**Comment by ildar** [comment]
жаль

**Comment by ildar** [comment]
Могу я предложить пересмотреть решение?
eng.: Re-triage?
