### ISSUE TITLE
Color of "Hamburger Menu" icon

### ISSUE THREAD

**Issue by Valdnet** [foobnix/LibreraReader#744]
When the application theme is set to "Dark OLED", the application menu icon is not visible:

![obraz](https://user-images.githubusercontent.com/47037905/144564780-8345fc24-67a0-4afd-bd08-131a6e683ed4.png)

When the application theme is set to "Dark", the application menu icon should be white:

![obraz](https://user-images.githubusercontent.com/47037905/144564104-f100d6fa-1958-46ee-a7c1-49d26b578684.png)

Issue that the "Hamburger Menu" icon does not change color for the corresponding theme.

Apps:
Android 10
Librera 8.4.6

**Comment by foobnix** [comment]
fixed
