### ISSUE TITLE
Will there be iOS app please?

### ISSUE THREAD

**Issue by zxkmm** [foobnix/LibreraReader#749]
I love this app and I’ll pay for it if there’s iOS app. Thank you very much!

**Comment by maximilianduell** [comment]
It is highly nontrivial to port native android applications to iOS, essentially you have to rewrite almost the full program.
For an iOS app with similar (or perhaps, even greater) capabilities check out e.g. [goodreader](https://apps.apple.com/de/app/goodreader-pdf-editor-viewer/id777310222).

**Comment by zxkmm** [comment]
> It is highly nontrivial to port native android applications to iOS, essentially you have to rewrite almost the full program.
> For an iOS app with similar (or perhaps, even greater) capabilities check out e.g. [goodreader](https://apps.apple.com/de/app/goodreader-pdf-editor-viewer/id777310222).

Thank you very much for your answer, but still I think librerareader is better than goodreader.
