### ISSUE TITLE
[ Request ] [ f-droid ] Is it possible to remove unused resources to reduce the apk install size?

### ISSUE THREAD

**Issue by a-pav** [foobnix/LibreraReader#758]
I don't know why apk size on f-droid is so big compared to apks on /releases page.
Most likely because of bundling multiple DPI resources in one apk, but I'm curious to know how is it different from the apks on /releases page? Don't they support multiple DPIs as well? Then how come that their size is smaller?

And as an alternative, is it possible to remove unused resources after first run like it's [talked about here](https://stackoverflow.com/questions/38336483/android-removing-unused-resolution-specific-drawables-on-first-run)?

**Comment by foobnix** [comment]
F-Droid not support multi platform apk files, you can download small apk here beta.librera.mobi

**Comment by a-pav** [comment]
Thanks for prompt reply but unfortunately I didn't get the answers to any of my questions.. :/

I sure know that F-Droid has no support for multiple platforms and DPIs (after all, there's only one apk file for download, it has to support all platforms and DPIs, obviously). Same is true about [github releases](https://github.com/foobnix/LibreraReader/releases) page. But still, github releases have a smaller size. Can I know why?

> F-Droid not support multi platform apk files

Do you mean that F-Droid can't follow the same build procedure you do for github releases?

**Comment by foobnix** [comment]
I can prepare 4 apks (arm, arm64,x86, x86_64) and do it for Google Play and for testing purposes, but F-Droid don't want to split.
I can upload 4 apks for github release page also.
4 apks is take more space (63.3mb) then one full apk(39.1mb)
Just download here http://beta.librera.mobi/ or on Google Play

**Comment by foobnix** [comment]
One more remark, F-Droid build use Mupdf 1.16 but Librera  mupdf 1.11  (old but smaller size)

**Comment by a-pav** [comment]
Oh... now I see!
So the F-Droid apk is a bundle of arm, arm64, x86, x86_64 (4 arch) while the [releases](https://github.com/foobnix/LibreraReader/releases) (specially the one I was looking at) was only an `arm`,  (15 MB).

Thank you for your clarification :)

**Comment by chromer030** [comment]
@foobnix 
Please upload splitted apks on github release on every release.
Thanks.
