### ISSUE TITLE
Preferences Window Blank

### ISSUE THREAD

**Issue by FrenchToucan** [foobnix/LibreraReader#764]
![Screenshot_20211230-234327](https://user-images.githubusercontent.com/41240662/147803842-eab4a051-69d0-433e-b937-0e8603a17aef.png)

Preferences window is blank, as shown above. Tried both Day and Night mode. Tried ePub and PDFs. Version 8.4.25-fdroid (116-fdroid).

**Comment by Vade86** [comment]
Yes can confirm this.
Using version 8.4.25-Fdroid in Android 11. This bug appeared after the above update.

**Comment by TheLastZombie** [comment]
Seems this is already fixed in the latest version (see #762).

**Comment by FrenchToucan** [comment]
> Seems this is already fixed in the latest version (see #762).

Got the update through f-droid this morning and it is fixed. Thanks for pointing that out. Looks like my bug was a dupe, anyways.
