### ISSUE TITLE
Some strings are still using the system language even after changing that of the app

### ISSUE THREAD

**Issue by asereze** [foobnix/LibreraReader#773]
My phone has Italian as system language, and the three strings related to the reading modes (Scroll, Book and Musician) keep staying in Italian even after I switch to another language from the options, no matter what language it is. It happens both while selecting them and in the reading screen.

![photo_2022-01-28_15-37-23](https://user-images.githubusercontent.com/11271324/151566625-404c477c-bcd3-459f-adcc-6e32b5ef70d6.jpg)
![photo_2022-01-28_15-37-24](https://user-images.githubusercontent.com/11271324/151566811-c2244f2a-060d-458b-bdb5-142002f49778.jpg)
![photo_2022-01-28_15-45-38](https://user-images.githubusercontent.com/11271324/151567248-07587598-80a9-4375-96c8-6081aa392fa0.jpg)

**Comment by foobnix** [comment]
you can press "Edit modes" link (bottom right) in the dialog to set any names you want.
Or you can long-press on the "Edit modes" link and will be the default name in the current language.
