### ISSUE TITLE
evil epubs

### ISSUE THREAD

**Issue by Dmole** [foobnix/LibreraReader#775]
A security test report would be nice

https://youtu.be/ixSZyuPsXNU

https://github.com/DistriNet/evil-epubs

and if there are any issues disable by default the features that cause them.

**Comment by foobnix** [comment]
Librera is secure because it does not use the web-http rendering engine (MuPdf uses custom rendering) and does not support javascript.
The F-Droid version does not have internet access.
thanks for the information
