### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [foobnix/LibreraReader#778]
```
+ ./link_to_mupdf_1.16.1.sh
MUPDF : 1.16.1
================== 
==================
make: *** No rule to make target 'release'.  Stop.
```

Could you please take a look? Thanks!

**Comment by foobnix** [comment]
I did not change the build process, it works fine on my computer

./link_to_mupdf_1.16.1.sh 
MUPDF : 1.16.1
================== 
fatal: destination path 'mupdf-1.16.1' already exists and is not an empty directory.
==================
make build=release
make[1]: Entering directory '/home/dev/git/LibreraReader/Builder/mupdf-1.16.1'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/dev/git/LibreraReader/Builder/mupdf-1.16.1'
make: Nothing to be done for 'generate'.
==================
ndk-build: /home/dev/Android/Sdk/ndk/23.1.7779620/ndk-build
================== 
[armeabi-v7a] Install        : libantiword.so => libs/armeabi-v7a/libantiword.so
[armeabi-v7a] Install        : libmobi.so => libs/armeabi-v7a/libmobi.so
[armeabi-v7a] Install        : libmypdf.so => libs/armeabi-v7a/libmypdf.so
[arm64-v8a] Install        : libantiword.so => libs/arm64-v8a/libantiword.so
[arm64-v8a] Install        : libmobi.so => libs/arm64-v8a/libmobi.so
[arm64-v8a] Install        : libmypdf.so => libs/arm64-v8a/libmypdf.so
[x86] Install        : libantiword.so => libs/x86/libantiword.so
[x86] Install        : libmobi.so => libs/x86/libmobi.so
[x86] Install        : libmypdf.so => libs/x86/libmypdf.so
[x86_64] Install        : libantiword.so => libs/x86_64/libantiword.so
[x86_64] Install        : libmobi.so => libs/x86_64/libmobi.so
[x86_64] Install        : libmypdf.so => libs/x86_64/libmypdf.so
==================
MUPDF: /home/dev/git/LibreraReader/Builder/mupdf-1.16.1/platform/librera
LIBS: /home/dev/git/LibreraReader/Builder/../app/src/main/jniLibs

**Comment by linsui** [comment]
Our patch broke something. We link the mupdf source code. I change symlink to copy and it works now. Thanks!
