### ISSUE TITLE
Exclude junrar from fdroid flavor

### ISSUE THREAD

**Issue by linsui** [foobnix/LibreraReader#794]
Could you please exclude junrar from fdroid flavor? It's not licensed under an FOSS license. See https://fedoraproject.org/wiki/Licensing:Unrar. Thanks!

**Comment by licaon-kter** [comment]
Any news?

**Comment by Valdnet** [comment]
@licaon-kter Currently, there will not be a new version so soon. See: https://github.com/foobnix/LibreraReader#librera-reader

**Comment by licaon-kter** [comment]
@Valdnet oh, stay safe then :+1:

**Comment by Valdnet** [comment]
@licaon-kter Right now my country is safe because it belongs to NATO, but we have to worry about @foobnix to win this war.

**Comment by linsui** [comment]
@foobnix Glad to see you back! Any news here?

**Comment by foobnix** [comment]
It's looks like the license is changed https://github.com/junrar/junrar/blob/master/LICENSE
I don't see the problem with this lib in the application

**Comment by linsui** [comment]
It's not changed. It's still the UNRAR license.

**Comment by linsui** [comment]
Thanks! I'll update the commit in the F-Droid metadata.

**Comment by linsui** [comment]
Done. https://gitlab.com/fdroid/fdroiddata/-/commit/a408d51a9085e61c0271ed7cff76569a39399603 

https://github.com/foobnix/LibreraReader/blob/0dbd10c4ebf2e232152b1bc81b10caa9e30e8a73/Builder/link_to_mupdf_1.20.0.sh#L24

This line looks weird to me. The directory already exists.
