### ISSUE TITLE
Calibre, OPDS catalogs and IPv6

### ISSUE THREAD

**Issue by Dunrar** [foobnix/LibreraReader#798]
I don't wan't to be distasteful by opening this issue in this time of crisis. I hope that someday soon the conflict in your country will come to an end. I'll just leave this here until then:

I have trouble connecting to my Calibre Content Server. Calibre and the content server are reverse-proxied and I can reach both via my domain in the browser but not with the Librera app. When using Calibre-Web OPDS it doesn't work either, but downloads just fine in the browser. No attempt of accessing or logging in to the server can be observed in the logs when using the app.

My suspicion is that it might be because my ISP uses DS-Lite, so I don't have my own public IPv4 address, DuckDNS returns only my servers IPv6.  As fewer and fewer people have their own IPv4 address, it might be worth looking into. 

Thanks and stay safe!

**Comment by foobnix** [comment]
please add some link url to check and fix
