### ISSUE TITLE
Weird issue with toolbar ? 

### ISSUE THREAD

**Issue by drishal** [foobnix/LibreraReader#802]
there seems to be a really weird issue with toolbar (not sure if I am doing it wrong)
once I have opened the book and the toolbar hides there is NO way to bring it back 
![image](https://user-images.githubusercontent.com/32875739/165792594-d67b9547-2991-4293-bde9-f8f373329041.png)
I cannot swipe it, tap on the edges to bring it back, nothing

it shows up only when the document is loading 

![image](https://user-images.githubusercontent.com/32875739/165792773-ba888fef-aea7-47ff-b7e0-dd26b2a8d15b.png)

Rom: crdroid 8.4 (android 12.1)

**Comment by foobnix** [comment]
just single tap in the center of the document should make toolbar visible

**Comment by drishal** [comment]
> just single tap in the center of the document should make toolbar visible

Aah ok thanks for that 😅
