### ISSUE TITLE
Issues about searching

### ISSUE THREAD

**Issue by Iey4iej3** [foobnix/LibreraReader#819]
It seems to me that Librera missed a lot of occurrences during searching.

For example, I tried to search keyword `idempotent` in this [book](https://www.math.ias.edu/~lurie/papers/SAG-rootfile.pdf), and it did not hit any occurrence in the first several hundred pages. However, this word appears, say, on page 246.

Librera Reader 8.4.52-fdroid

**Comment by foobnix** [comment]
I check, librera and other reader finds this word on 131 page
please update to the final version beta.librera.mobi

**Comment by Iey4iej3** [comment]
Yes, fixed in 8.5.37-fdroid.
