### ISSUE TITLE
Sometimes Images have blank pages after or/and before

### ISSUE THREAD

**Issue by MrComexs** [foobnix/LibreraReader#848]
I don't know why but sometimes images have a blank page after and before but sometimes its only after. The only time I don't see a blank page after a image is when its next to another image but only a few rare times.

Librera PRO
version 8.5.12-fdroid(120-fdroid)
on a SM-T870 (Galaxy Tab S7)
I also use two page mode all the time but this bug still applies to one page mode.

**Comment by foobnix** [comment]
please try beta.librera.mobi
