### ISSUE TITLE
Hangs when trying to open particular books then won't open anything else

### ISSUE THREAD

**Issue by distbit0** [foobnix/LibreraReader#855]
I am experiencing a bug whereby librera hangs on the "Pease wait..." banner when opening some books after which it then won't open any other books (clicking on them or long clicking and then pressing on "Read!" doesn't do anything. 

This even persists between quitting the app, clearing cache, re-installing the app and restarting my phone. 

I still can't open the book in question, but it is: https://mega.nz/file/YtwhCJCT#QZqzgQQngegxxE_uZ1ynmgEQqVVWl-ajThad_HFQYG4

I can now for some reason open most other books easily enough, after restarting the app several more times. They still take about 10s to open though.

My config file is: https://file.io/hgFhTMdc8jCK

I am using 8.5.0 F-Droid Android 11 TCL UI 3.0.1

**Comment by foobnix** [comment]
please try with the final version [beta.librera.mobi](http://beta.librera.mobi)

**Comment by distbit0** [comment]
Hmm seems to work a bit better, although still takes like 30 seconds to open some ebooks...
