### ISSUE TITLE
Issues about CJK Font.

### ISSUE THREAD

**Issue by mori-oh** [foobnix/LibreraReader#859]
I want this app to change the standard character shape　for each language.

I often read PDFs with no fonts embedded.
When you open the PDF with this app, the glyphs are in Chinese, not Japanese.
It would be great if we could make the glyphs of Japanese when the language of the app was set to Japanese, and the glyphs of Chinese and Korean when set to Chinese and Korean, respectively.

This is a CJK-specific issue, so please refer to it here. https://en.wikipedia.org/wiki/Han_unification

The correct glyph (Displayed in mupdf)
![The correct glyph (Displayed in mupdf)](https://user-images.githubusercontent.com/105188440/178133085-ab60fcda-5f3b-4aa8-8679-de671e670605.png)

This app
![This app](https://user-images.githubusercontent.com/105188440/178133099-87ae763f-cb87-4ea1-8aff-00ba168ae57e.png)

**Comment by foobnix** [comment]
Please also try other fonts
![Screenshot from 2022-07-11 12-45-10](https://user-images.githubusercontent.com/432440/178237201-449dced9-658c-4f53-8b5c-21cd4fa731f7.png)

**Comment by mori-oh** [comment]
I understand, but that doesn't help.
I'm using the latest version for F-Droid, but it's still in Chinese glyphs.
Also, when I open the PDF, I don't see any items like "Document Style" or "Fonts" on the settings screen.

**Comment by foobnix** [comment]
please attach some book sample to verify  
Sorry, style settings only for epub docs

**Comment by mori-oh** [comment]
Use this.
http://cruel.org/freeware/cathedral.pdf

**Comment by foobnix** [comment]
update mupdf in librera to the final veraion 1.20.2
