### ISSUE TITLE
Translate text in book use  libretranslate

### ISSUE THREAD

**Issue by winterwolf45** [foobnix/LibreraReader#870]
Hi Thanks for created this software
### When I first selecte text and select translate it use icon libretranslate ( into libreraReader) it's OK but if I again  trying for translate it's can't work ( libreReader  can't paste into libretranslate for translate ) but if I close complete libretranslate and open it again libreaReader work .

**Comment by foobnix** [comment]
libretranslate should support this functionality and then Librera can send the text to this app
