### ISSUE TITLE
[BUG] Cannot re-open PDF documents with saved highlights

### ISSUE THREAD

**Issue by PassionateG1t** [foobnix/LibreraReader#872]
**OS:** Android 12

**Affected versions:** I tried 8.5.12 ~> 8.5.37 from f-droid

**Bug reproduction:**

1. Open any pdf document
2. Select word(s) and use fairly new highlighting feature
3. Save file when closing
4. Reopen file

**resulting behavior:** Blank page and a toast pops up saying "Unexpected error has occured

**expected behavior:** PDF doc open normally with all highlights preserved

**Comment by foobnix** [comment]
fixed in new beta.librera.mobi
