### ISSUE TITLE
TTS

### ISSUE THREAD

**Issue by Dmole** [foobnix/LibreraReader#874]
is not working near the end of some books.
There is a brief notification that indicates 108% 1181/1093 vs the 1182/1202 in the app.

**Comment by rlpowell** [comment]
Do you have a repro case?  Like, a book file we can legally get where this happens?

**Comment by Dmole** [comment]
@rlpowell I can't even reproduce this issue on the book that was previously showing the issue on 2 separate devices, so it's clearly intermittent, or conditional on something...
