### ISSUE TITLE
No Network Tab

### ISSUE THREAD

**Issue by tonydero** [foobnix/LibreraReader#883]
I apologize if there is a simple answer to this. 

I'm trying to add an OPDS feed. I've seen that Librera implements this in the Network tab. However, no matter what version I install on my phone, the Network tab is not there. It isn't in the list of tabs in the preferences either.

I've installed from F-Droid and Google Play (both regular and Pro) and the apk from the releases here. Nothing.

Is there a setting I'm missing somewhere that enables it?

Thanks for any help.

**Comment by foobnix** [comment]
F-Droid version is without internet functionality

**Comment by tonydero** [comment]
Sorry if there was miscommunication, but I said I installed the Google Play version and it still wasn't there either. What is the proper procedure for switching to the Google Play version so I *can* access the network tab?

**Comment by tonydero** [comment]
For anyone else that experiences this. There is a persistent file of some sort that must be deleted from the phone in the filesystem after uninstalling, otherwise it will never show up no matter what version you install.

Apologies @foobnix.

**Comment by foobnix** [comment]
If you install the PRO version you just need to enable it (left menu - checkbox Network tab) or reset the profile to default changes.
F-Droid and PRO are the same configuration on device

**Comment by tonydero** [comment]
I did check that when I installed the PRO version, but it wasn't there. So I guess my method deleting the files is a workaround.

**Comment by tralph3** [comment]
Why no internet functionality in the F-Droid version? I really don't want to install it from the Play Store.

**Comment by foobnix** [comment]
>Why no internet functionality in the F-Droid version? 
For security reasons, which many users like.

**Comment by Korb** [comment]
> For security reasons, which many users like.

How did the developers of FOSS apps like [PageTurner](https://f-droid.org/en/packages/net.nightwhistler.pageturner/), [KOReader](https://f-droid.org/en/packages/org.koreader.launcher.fdroid/), and [Document Viewer](https://f-droid.org/en/packages/org.sufficientlysecure.viewer/), which both work with OPDS and are published on F-Droid, get around the OPDS security issue?
