### ISSUE TITLE
TTS is broken

### ISSUE THREAD

**Issue by Crissium** [foobnix/LibreraReader#888]
I'm on Android 12. TTS works perfectly on my older Android 6 device.

Version: 8.5.45-fdroid

Details: in the 'TTS Settings' tab, 'Voice' only shows the trashy TTS engine bundled with my system, even though I have already installed Google TTS and made it default. So I disabled the system TTS package with `adb`. But now 'Voice' only displays `--- ---`. When I tap the 'play' icon, I am asked to install the Google Speech Service app, which I've installed.

**Comment by sak96** [comment]
Hey i am also facing the same issue. Both in fdriod and pro version.

**Comment by sak96** [comment]
no obvious change which might have caused the issue which could be inferred from the [diff](https://github.com/foobnix/LibreraReader/compare/8.5.37...8.5.45).

**Comment by Crissium** [comment]
> no obvious change which might have caused the issue which could be inferred from the [diff](https://github.com/foobnix/LibreraReader/compare/8.5.37...8.5.45).

Actually I have tried downgrading to 8.5.37 and the problem still persists

**Comment by MI3Guy** [comment]
I downgraded to 8.5.37 and it works again.

**Comment by sak96** [comment]
> > no obvious change which might have caused the issue which could be inferred from the [diff](https://github.com/foobnix/LibreraReader/compare/8.5.37...8.5.45).
> 
> Actually I have tried downgrading to 8.5.37 and the problem still persists

when i tried to downgrade it did not allow me.
i had to uninstall only then i could install 8.5.37 and the problem was gone.

**Comment by Crissium** [comment]
Yeah, thank you. I uninstalled 8.5.45 and reinstalled 8.5.37 and TTS now works again.

**Comment by sak96** [comment]
hi @foobnix is it possible for releasing a beta with this permission added ?
I am having issue setting up `gradle`.

I have tested even the latest `8.6.15` build as well it also has issue with tts.

```AndroidManifest.xml
<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
```

**Comment by sak96** [comment]
i am not able to generate fdroid apk.

if i use java11 i get following error
```
Exception while marshalling /opt/android-sdk/build-tools/31.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/tools/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/31.0.0/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/tools/package.xml. Probably the SDK is read-only
Checking the license for package Android SDK Platform 31 in /opt/android-sdk/licenses
License for package Android SDK Platform 31 accepted.
Preparing "Install Android SDK Platform 31 (revision: 1)".
Warning: Failed to read or create install properties file.
```
and `sdkmanager --licenses`
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
1 sak@godbless in temp/j
```

if i use java8 (or 1.8. reminds me why i quit java)

```
* Where:
Build file '/home/sak/temp/java/LibreraReader/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     Your current JDK is located in  /usr/lib/jvm/java-8-openjdk/jre
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
  ```

**Comment by foobnix** [comment]
@sak96 do you think QUERY_ALL_PACKAGES permission fix the TTS on your device?

**Comment by foobnix** [comment]
fix will be soon

**Comment by sak96** [comment]
i have build a [release](https://github.com/sak96/LibreraReader/releases/tag/8.6.15-fixtts.0) adding this and created a pr with same.

The change is adding back permission in mainifest
```AndroidManifest.xml
<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
```
can any one else validate if this is working for you ?

**Comment by sak96** [comment]
> @sak96 do you think QUERY_ALL_PACKAGES permission fix the TTS on your device?

yeah i did finally manage to get the package build. This fix does show the rhvoice tts engine.

i think i did not recognize that ndk was required. so stupid of me to not realize mupdf was getting linked via ndk.

**Comment by sak96** [comment]
going through commit ddfa3a6800bfa77c9a417dea4d0b856cf610c55c, looks like you want to use [queries](https://developer.android.com/guide/topics/manifest/queries-element) ?

**Comment by sak96** [comment]
Use queries instead of `uses-permission` this also fixes the issue.
 
 Upload the release.

**Comment by foobnix** [comment]
Google play do not recommend to use QUERY_ALL_PACKAGES, please check beta.librera.mobi with fix

**Comment by sak96** [comment]
> Google play do not recommend to use QUERY_ALL_PACKAGES, please check beta.librera.mobi with fix

Agreed. And hence i have added this in the pr. #893 
```AndroidManifest.xml
        <intent>
          <action android:name="android.intent.action.TTS_SERVICE" />
        </intent>
    </queries>
```

**Comment by sak96** [comment]
> Google play do not recommend to use QUERY_ALL_PACKAGES, please check beta.librera.mobi with fix

this works.
