### ISSUE TITLE
[Feature Request] List unread books.

### ISSUE THREAD

**Issue by zelch** [foobnix/LibreraReader#889]
I'm not really asking for this to be implemented...  I'm happy to write the feature and make a pull request, but I'd like feedback on the specifics.

What I'm looking for is the ability to list unread books, and sort those results in all the usual ways.

The biggest question is how to define unread, I'm pretty sure that the first (and easiest) step is to add PROGRESS(FileMetaDae.Properties.IsRecentProgress, AppState.MODE_PROGRESS) to SEARCH_IN in AppDB.java, along with adding AppState.MODE_PROGRESS of course.  That would allow search by progress, but, of course, you don't want to search for a specific value, so that's not _horribly_ useful by itself.

Then again in AppDB, adding specific logic for searching by progress, either with a fixed value like ge(0.01), or allowing the specific progress value to be specified.

To make it another tab, I'm assuming that I'd need a glyph to use in PopupHelper, and to make changes to SearchFragment2 and UIFragment.  The glyph would probably be the hardest part for _me_, so I'd probably throw in a placeholder.

Thoughts?  And for the author specifically...  Would you merge this if I wrote it cleanly?  Do you have any preferences for anything in here?

**Comment by foobnix** [comment]
I have added the feature "Hide unread books from the library or from browse view, just enable it in the library settings or for the folder view setting.
It hides only the books that have progress of reading of 100%, so if you want to hide some books just close this book on the last page.
![Screenshot-2022-08-19-15-07-54](https://user-images.githubusercontent.com/432440/185931004-b706d4d8-5a50-4676-a3b8-7db552140010.png)

**Comment by zelch** [comment]
Wonderful, thank you! :)
