### ISSUE TITLE
Accept custom size from EPUB

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [foobnix/LibreraReader#890]
_The Manual of the Phonetic Symbol of Mandarin Chinese_ is published in EPUB, which has customized font size and image size. However Librera does not accept them. It would be nice to have an option to let the document load in its own font size and image size.

This is available here: https://web.archive.org/web/20220622110858/https:/language.moe.gov.tw/001/Upload/files/site_content/M0001/juyin/index.html

**Comment by foobnix** [comment]
try to change styles settings to Document
![Screenshot-2022-08-26-10-56-55](https://user-images.githubusercontent.com/432440/186852787-ee7bd1de-7452-445f-b746-79eb870595b6.png)

**Comment by KrasnayaPloshchad** [comment]
No, it doesn’t help

**Comment by KrasnayaPloshchad** [comment]
Let’s what it looks like in MuPDF Viewer
![Screenshot_20220827-124950](https://user-images.githubusercontent.com/10364351/187015218-95f83209-7718-42d6-8e1b-38b36ef28e17.png)
After I open with Liberera, neither *Document + User-defined*, *Document* or *User-defined* could affect the visual appearance.
![Screenshot_20220827-125743](https://user-images.githubusercontent.com/10364351/187015314-6fc76368-3f81-4897-937b-9d80393219de.png)

**Comment by foobnix** [comment]
could you please attache this book to fix the app

**Comment by KrasnayaPloshchad** [comment]
This book can be get from here:
https://web.archive.org/web/20220622110858/https:/language.moe.gov.tw/001/Upload/files/site_content/M0001/juyin/epub/zh.epub

**Comment by foobnix** [comment]
please test in beta set custom image scale factor
![Screenshot-2022-08-29-12-12-55](https://user-images.githubusercontent.com/432440/187168158-281f1bc0-bf95-4a22-a0cd-660d63b23978.png)

**Comment by KrasnayaPloshchad** [comment]
It looks works for me, but I still want styling from document side.
