### ISSUE TITLE
[Feature Request] Load font from EPUB

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [foobnix/LibreraReader#891]
_The Manual of the Phonetic Symbol of Mandarin Chinese_ is released in EPUB format, which includes WOFF font file to render text. But the font doesn’t works in Librera.

http://language.moe.gov.tw/001/Upload/files/site_content/M0001/juyin/index.html

**Comment by foobnix** [comment]
please check beta.librera.mobi - I have added more fonts
