### ISSUE TITLE
Latest version fails to detect TTS 

### ISSUE THREAD

**Issue by Hate9** [foobnix/LibreraReader#901]
As of the latest version (8.5.45-fdroid), Librera cannot find RHVoice, or, when I downloaded it to check, Google Voice Services.
I am on CalyxOS 3.7.0.
I've downgraded to 8.5.37-fdroid, and it works again, so it's definitely something in the update.

**Comment by sak96** [comment]
the fix is merged. check issue #888. 

in case you want to test the fix then check [this](https://github.com/foobnix/LibreraReader/releases/tag/8.6.17).

may take some time to release the apk.
