### ISSUE TITLE
Why the status bar and menus won't hide when reading?

### ISSUE THREAD

**Issue by XDTZ** [foobnix/LibreraReader#920]
Tested on: Fairphone 4 Android 11 build 142, Android 5.1 of DPT-RP1, 
I tried hiding everything in the status bar menu. Not working at all. Everything still shows up to block my reading area. I don't know if there's forum for these small stuff so I posted here.

**Comment by breaking-loss** [comment]
To hide status bar use this :
Open a PDF 
Click on preferences (settings icon )
Go to status bar
Uncheck Show status bar

Or did you mean this isn't working

**Comment by XDTZ** [comment]
![Screenshot_20220905-164139](https://user-images.githubusercontent.com/9079219/188407255-d2cee7e0-b184-4036-a445-5af4b8f2cfa3.png)
I've unchecked everything.

**Comment by foobnix** [comment]
The status bar is not displayed if you hide UI buttons and read the book
![Screenshot-2022-09-05-15-56-25](https://user-images.githubusercontent.com/432440/188454692-4922a33b-9d61-44cb-9530-dd1fb0f430ec.png)

**Comment by XDTZ** [comment]
[Video showing it not working](https://drive.google.com/file/d/1P9KhDjHJNtkc1KMVKTgtpNdqQFkHAh13/view?usp=drivesdk) 
What could be wrong? It just won't hide.

**Comment by breaking-loss** [comment]
> [Video showing it not working](https://drive.google.com/file/d/1P9KhDjHJNtkc1KMVKTgtpNdqQFkHAh13/view?usp=drivesdk) What could be wrong? It just won't hide.

Click in the middle to hide it ,still isn't working try to reinstall it from f-droid . I had this issue but after reinstalling it it worked

**Comment by foobnix** [comment]
It's look like you have enabled Accessibility mode for blind persons they no need to hide UI, just uncheck this option or reset the profile to default values.

![Screenshot-2022-09-06-09-29-37](https://user-images.githubusercontent.com/432440/188562879-132cd2a7-56d7-4cc6-848f-654ec2a9fca4.png)
![Screenshot-2022-09-06-09-30-09](https://user-images.githubusercontent.com/432440/188562874-634128b4-4025-432b-825b-e87eb3cd57ce.png)
