### ISSUE TITLE
Feature Request: Import/extract tags from books downloaded from Archive Of Our Own (AO3)/OTWArchive

### ISSUE THREAD

**Issue by LiftedStarfish** [foobnix/LibreraReader#924]
The website [Archive Of Our Own](https://archiveofourown.org/) has a very useful tagging system for stories uploaded to the site. It also allows users to download stories uploaded there as a PDF, EPUB, AZW3, MOBI, and HTML. I cannot speak for the other formats, but I know that the EPUB versions of the stories have a consistent method for bundling the site's tags in with the EPUB file.

I'm requesting a feature that would allow users to extract the tags from any story which is formatted as an EPUB generated by AO3 (although, it's probably an OTWArchive thing, not just AO3)?

This would be very helpful to me. I download a _lot_ of fanfiction from the site, and I have _no_ interest in going through and manually tagging every story that I download. It would be much simpler if I could just go into the tag settings of a story, tap on a button that says "Import AO3/OTWArchive tags", and then it's done. This would then allow me to easily search through the dozens of fanfics that I've downloaded for multiple fandoms, rather than having to enter each one manually and look at the tags on the first or second page (part of the same xhtml file though).

**Comment by foobnix** [comment]
As I see, all tags are saved in the epub as a genre, so you can easily find all books by genre tag
![Screenshot from 2022-09-14 15-43-16](https://user-images.githubusercontent.com/432440/190157145-2d781074-3efe-4754-9db5-383f8538eff9.png)

**Comment by LiftedStarfish** [comment]
Wow, this was not something that I was aware of. Thank you! Sorry for wasting your time and not checking more thoroughly.
