### ISSUE TITLE
Google translate cause "unexpected error" and crash on Android 13

### ISSUE THREAD

**Issue by GhostScript0r** [foobnix/LibreraReader#930]
After updating my Google Pixel 6 to Android 13, using Google translate on highlighted text no longer works. 

If the reader app is set to immediately translate selected word, upon selection a banner will show saying "an unexpected error has occured". If the app is set to show a context menu upon text selection, choosing Google Translate in the context menu will cause the app to crash.

Only Android 13 is affected. On another device of mine running Android 12L (LineageOS 19.1) this issue doesn't occur.

**Comment by foobnix** [comment]
Fixed in beta. I think the bug in Google Translate, other dict can handle the text
