### ISSUE TITLE
Feature request: Cache files to improve load time

### ISSUE THREAD

**Issue by SMSourov** [foobnix/LibreraReader#944]
### _Issue:_
When a book is opened for the first time it takes some time(probably 1/2 seconds, depending on the book) to load and it is opened. Not a big deal.
But when the book is opened multiple times, those 1/2 seconds become a big deal. Taking those 1/2 seconds every time when the book is open makes a bad user experience.

### _Expected behavior:_
When a book is opened, it can be assumed that the book will be opened again. So that book will be cached. As a result, when a book will be opened, it may take a few seconds for the first time. But, from the second time, it will not take those seconds. It will open the book immediately. Hence, the user will have a good experience.
Moreover, let's assume a book had not been opened for 30 days. It can be assumed that, that would not be opened soon. That book will not be cached anymore and will also be removed from the recent book or currently reading book list.

**Comment by SMSourov** [comment]
Kindly keep this in mind. I'm sure that it will improve the user experience.

**Comment by SMSourov** [comment]
I'm hoping that you would give a feedback.

**Comment by chemicalcain** [comment]
The development of Librera is currently frozen due to the war in Ukraine. I worry your request will be hard to find once development resumes. Please change the issue title to "Feature request: Cache files to improve load time"

**Comment by SMSourov** [comment]
> The development of Librera is currently frozen due to the war in Ukraine. I worry your request will be hard to find once development resumes. Please change the issue title to "Feature request: Cache files to improve load time"

Done.

**Comment by ThaChillera** [comment]
+1, I have a 20mb epub file, loading takes 5 seconds, would be great if this could be cached somehow

**Comment by foobnix** [comment]
Please check beta.librera.mobi I haved added acceleration opening (cache) on second+ attempts

**Comment by SMSourov** [comment]
Thank you. I'll check that.

**Comment by SMSourov** [comment]
Yes, I was waiting for this improvement. Thank you. 🥰💖
